# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: packaging/.gitpod.Dockerfile

tasks:
  - name: init and run
    init: |
      yarn install
      yarn build:dst:pre
    command: |
      yarn sd
  - name: command line for free
    command: echo "Welcome to APITable"
    openMode: split-right
  - name: startup APITable
    command: |
      make up
              

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
