version: '3'

services:
  test-mysql:
    container_name: test-mysql
    image: mysql:8.0.32
    networks:
      - apitable
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=apitable_test
      - MYSQL_USER=apitable
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    command: ['mysqld', '--sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 30s
      timeout: 10s
      retries: 5

  test-init-db:
    container_name: test-init-db
    image: gradle:jdk8
    networks:
      - apitable
    working_dir: /data
    volumes:
      - ./init-db:/data
    environment:
      - DB_HOST=test-mysql
      - DB_PORT=3306
      - DB_NAME=apitable_test
      - DB_USERNAME=apitable
      - DB_PASSWORD=password
      - DATABASE_TABLE_PREFIX=apitable_
    entrypoint: ./gradlew update

  test-redis:
    container_name: test-redis
    image: redis:7.0.8
    networks:
      - apitable
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  test-rabbitmq:
    container_name: test-rabbitmq
    image: rabbitmq:3.11.9-management
    networks:
      - apitable
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=apitable
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  apitable:
    driver: bridge