= 开发实践 之 本地数据库

== 1.概述

- 背景：本地研发依赖线上集成环境数据库，坏处非常明显（直接影响验证 DB migration 脚本、后端数据逻辑和单元测试）。应该有简便方式启动并配置好本地开发环境。
- 技术定位：中级
- 目标群体：研发
- 技术应用场景：基础设施即代码（Infrastructure as Code）理念在本地开发中的体现之一。
- 整体思路：结合 docker、devtools 脚本和基于 env 的配置，简单启动数据库供后端服务使用。

== 2.道理

=== 2.1 必要性

我们需要本地环境的数据库，原因包括这几方面。

==== 与公用数据解耦

- 开发中的功能会带来垃圾数据，请保持垃圾只会停留在自己家门前。
- 个人研发的使用不该占用公用的资源。

==== 写测试的需要

- 单元测试的要求是独立的、可重复的：任何时间以任何分组执行，测试所期待的断言结果都应该是确定的。所以测试的执行应该基于干净的数据环境。
- 测试的执行越快越能及时得到反馈，要求在连接数据库时能足够快。

==== 调试 DB migration 脚本的需要

- 难以想象研发做 DB migration 脚本调试时，直接在公用的线上数据库进行。

=== 2.2 最佳实践

==== 用容器工具以开发环境的配置启动数据库服务

可借助 docker-compose 工具简单地配置和启动数据库。

- Redis
- MySQL for dev（挂载磁盘以持久化数据）
- MySQL for test

==== 支持环境变量管理后端服务的配置
- 后端服务可借助 dotenv 列出环境变量并在启动时传入值覆盖配置。本地数据库的连接参数作为默认配置值；不在代码中暴露线上数据库地址。

==== 通过脚本简化开发者输入命令参数和环境变量
- 以一条命令取代一篇步骤说明文档，帮大家节省时间。 例如：私有化部署的 install.sh 把离散的安装步骤脚本化
- 鼓励 devtools 命令脚本，将带各种意图和参数的命令包装在脚本中，提供简洁的入口。

例如：vikadata-master 仓库里的 devtools.sh 提供若干帮助命令，执行创建数据库、执行 DB migration、启动 API 服务和初始化用户数据等本地开发环境常用操作。类似的还有 datasheet 仓库里的 Makefile 。

== 3 Dev 实操
=== 基础准备
代码仓库（分支：integration）

- db-manage
- vikadata-master - vikadata-websocket
- datasheet

工具

- docker + docker-compose （Docker Desktop for Mac）
- java (按 vikadata-master 仓库 README 的要求)

=== Devtools 命令解释
在 vikadata-master 仓库根目录有 devtools.sh 文件，从命令行执行
[source,shell]
----
$ ./devtools.sh
Please select what you want to do:
1) setup-redis                   5) migrate-mysql
2) setup-mysql                   6) setup-mysql-for-test
3) launch-service-api            7) init-users
4) run-tests                     8) prepare-client-release
----



目前涵盖命令的解释

1. setup-redis : 启动 Redis
2. setup-mysql : 启动用于开发的 MySQL 并更新 schema
3. launch-service-api : 构建并启动 API 服务
4. run-tests : 跑所有测试
5. migrate-mysql : 更新用于开发的 MySQL 的 schema
6. setup-mysql-for-test : 重建用于测试的 MySQL 并更新 schema
7. init-users : 初始化 5 个用户，登录帐密会显示在执行结果中
8. prepare-client-release ：准备数据用以调试 api/v1/client/entry

=== 首次初始化本地数据库

- ./devtools.sh 选 1 （setup-redis） 执行到结束
- ./devtools.sh 选 2 （setup-mysql） 执行完结束
- ./devtools.sh 选 3 （launch-service-api） 并保持运行
- 在另一个命令行窗口执行 ./devtools.sh 选 7 （init-users），留意结果内容

=== 日常操作

==== 从命令行重启 Java service API
- ./devtools.sh 选 3 （launch-service-api）

==== 重建测试数据库
- ./devtools.sh 选 6 （setup-mysql-for-test）

==== 更新用于开发的 MySQL 的 schema
- ./devtools.sh 选 5 （migrate-mysql）

启动全套本地服务 暂时无法在文档外展示此内容

== 4 CI 构建
=== 要求标准
- 构建脚本执行测试
- 测试应基于和生产环境同版本的数据库，独立、干净
- 测试数据库由代码在构建开始时初始化，在构建结束释放
- 测试数据库 schema 版本的代码应与管理生产环境数据库 schema 版本的代码相同

=== 操作参考
==== 支持的环境变量
与 MySQL / Redis docker image 支持的环境变量同名
[source,text]
----
MYSQL_HOST=mysql
MYSQL_PORT=3306
MYSQL_USERNAME=****
MYSQL_PASSWORD=****
MYSQL_DATABASE=****
MYSQL_USE_SSL=false

REDIS_HOST: redis
REDIS_PORT: 6379
----

==== 升级 MySQL schema 版本
git@git.vika.ltd:server/db-manage.git 是 MySQL schema 版本管理的独立仓库。

在 CI 上通过环境变量指定 MySQL DB 的连接信息执行脚本，可升级 schema 到代码当前最新。
[source,shell]
----
# 确保环境变量已生效再执行
./upgrade_db.sh
----

==== 跑 room-server 测试
git@git.vika.ltd:fe/datasheet.git 的 package 之一是 room-server ，他的测试从仓库根目录可以跑。
[source,shell]
----
# 先构建 room-server 的依赖
yarn build:dst:pre
----

默认配置项在 packages/room-server/src/env/.env.dev-test
[source,shell]
----
# 确保配置项的环境变量已生效再执行，否则应用默认配置项
yarn test:ut
----

==== 跑 Java backend 测试
git@git.vika.ltd:server/vikadata-master.git 是 Java backend 代码库，全部的测试可用 devtools 跑起来。

Service API 的默认配置项在 vikadata-service/vikadata-service-api/src/main/resources/application-local.yml
[source,shell]
----
# 确保配置项的环境变量已生效再执行，否则应用默认配置项
./devtools.sh run-tests
----

== 一些结论
- 本地造dev用的测试数据
- 测试本身创建自己需要的数据
- 线上环境的 db 只读权限
- 需要一个线上数据问题做 trouble shooting 的预案
- 数据不能离开所在环境
- Core 代码更改将触发依赖core的所有repo的测试