export const EXPAND_RECORD_OPERATE_BUTTON = 'EXPAND_RECORD_OPERATE_BUTTON';
export const EXPAND_RECORD_COMMENT_WRAPPER = 'EXPAND_RECORD_COMMENT_WRAPPER';
export const COMMENT_SUBMIT_BUTTON = 'COMMENT_SUBMIT_BUTTON';
export const EXPAND_RECORD_ACTIVITY_ITEM = 'EXPAND_RECORD_ACTIVITY_ITEM';
export const EXPAND_RECORD_DELETE_COMMENT_MORE = 'EXPAND_RECORD_DELETE_COMMENT_MORE';
export const NOTIFICATION_ITEM_RECORD = 'NOTIFICATION_ITEM_RECORD';
export const MODAL_FOOTER_BTN_CONFIRM = 'MODAL_FOOTER_BTN_CONFIRM';
