export const TIMEZONES = [
  {
    tzCode:'Pacific/Midway',
    utc:'-11:00'
  },
  {
    tzCode:'Pacific/Niue',
    utc:'-11:00'
  },
  {
    tzCode:'Pacific/Pago_Pago',
    utc:'-11:00'
  },
  {
    tzCode:'America/Adak',
    utc:'-10:00'
  },
  {
    tzCode:'Pacific/Honolulu',
    utc:'-10:00'
  },
  {
    tzCode:'Pacific/Rarotonga',
    utc:'-10:00'
  },
  {
    tzCode:'Pacific/Tahiti',
    utc:'-10:00'
  },
  {
    tzCode:'Pacific/Marquesas',
    utc:'-09:30'
  },
  {
    tzCode:'America/Anchorage',
    utc:'-09:00'
  },
  {
    tzCode:'America/Juneau',
    utc:'-09:00'
  },
  {
    tzCode:'America/Metlakatla',
    utc:'-09:00'
  },
  {
    tzCode:'America/Nome',
    utc:'-09:00'
  },
  {
    tzCode:'America/Sitka',
    utc:'-09:00'
  },
  {
    tzCode:'America/Yakutat',
    utc:'-09:00'
  },
  {
    tzCode:'Pacific/Gambier',
    utc:'-09:00'
  },
  {
    tzCode:'America/Los_Angeles',
    utc:'-08:00'
  },
  {
    tzCode:'America/Tijuana',
    utc:'-08:00'
  },
  {
    tzCode:'America/Vancouver',
    utc:'-08:00'
  },
  {
    tzCode:'Pacific/Pitcairn',
    utc:'-08:00'
  },
  {
    tzCode:'America/Boise',
    utc:'-07:00'
  },
  {
    tzCode:'America/Cambridge_Bay',
    utc:'-07:00'
  },
  {
    tzCode:'America/Chihuahua',
    utc:'-07:00'
  },
  {
    tzCode:'America/Creston',
    utc:'-07:00'
  },
  {
    tzCode:'America/Dawson',
    utc:'-07:00'
  },
  {
    tzCode:'America/Dawson_Creek',
    utc:'-07:00'
  },
  {
    tzCode:'America/Denver',
    utc:'-07:00'
  },
  {
    tzCode:'America/Edmonton',
    utc:'-07:00'
  },
  {
    tzCode:'America/Fort_Nelson',
    utc:'-07:00'
  },
  {
    tzCode:'America/Hermosillo',
    utc:'-07:00'
  },
  {
    tzCode:'America/Inuvik',
    utc:'-07:00'
  },
  {
    tzCode:'America/Mazatlan',
    utc:'-07:00'
  },
  {
    tzCode:'America/Ojinaga',
    utc:'-07:00'
  },
  {
    tzCode:'America/Phoenix',
    utc:'-07:00'
  },
  {
    tzCode:'America/Whitehorse',
    utc:'-07:00'
  },
  {
    tzCode:'America/Yellowknife',
    utc:'-07:00'
  },
  {
    tzCode:'America/Bahia_Banderas',
    utc:'-06:00'
  },
  {
    tzCode:'America/Belize',
    utc:'-06:00'
  },
  {
    tzCode:'America/Chicago',
    utc:'-06:00'
  },
  {
    tzCode:'America/Costa_Rica',
    utc:'-06:00'
  },
  {
    tzCode:'America/El_Salvador',
    utc:'-06:00'
  },
  {
    tzCode:'America/Guatemala',
    utc:'-06:00'
  },
  {
    tzCode:'America/Indiana/Knox',
    utc:'-06:00'
  },
  {
    tzCode:'America/Indiana/Tell_City',
    utc:'-06:00'
  },
  {
    tzCode:'America/Managua',
    utc:'-06:00'
  },
  {
    tzCode:'America/Matamoros',
    utc:'-06:00'
  },
  {
    tzCode:'America/Menominee',
    utc:'-06:00'
  },
  {
    tzCode:'America/Merida',
    utc:'-06:00'
  },
  {
    tzCode:'America/Mexico_City',
    utc:'-06:00'
  },
  {
    tzCode:'America/Monterrey',
    utc:'-06:00'
  },
  {
    tzCode:'America/North_Dakota/Beulah',
    utc:'-06:00'
  },
  {
    tzCode:'America/North_Dakota/Center',
    utc:'-06:00'
  },
  {
    tzCode:'America/North_Dakota/New_Salem',
    utc:'-06:00'
  },
  {
    tzCode:'America/Rainy_River',
    utc:'-06:00'
  },
  {
    tzCode:'America/Rankin_Inlet',
    utc:'-06:00'
  },
  {
    tzCode:'America/Regina',
    utc:'-06:00'
  },
  {
    tzCode:'America/Resolute',
    utc:'-06:00'
  },
  {
    tzCode:'America/Swift_Current',
    utc:'-06:00'
  },
  {
    tzCode:'America/Tegucigalpa',
    utc:'-06:00'
  },
  {
    tzCode:'America/Winnipeg',
    utc:'-06:00'
  },
  {
    tzCode:'Pacific/Easter',
    utc:'-06:00'
  },
  {
    tzCode:'Pacific/Galapagos',
    utc:'-06:00'
  },
  {
    tzCode:'America/Atikokan',
    utc:'-05:00'
  },
  {
    tzCode:'America/Bogota',
    utc:'-05:00'
  },
  {
    tzCode:'America/Cancun',
    utc:'-05:00'
  },
  {
    tzCode:'America/Cayman',
    utc:'-05:00'
  },
  {
    tzCode:'America/Detroit',
    utc:'-05:00'
  },
  {
    tzCode:'America/Eirunepe',
    utc:'-05:00'
  },
  {
    tzCode:'America/Grand_Turk',
    utc:'-05:00'
  },
  {
    tzCode:'America/Guayaquil',
    utc:'-05:00'
  },
  {
    tzCode:'America/Havana',
    utc:'-05:00'
  },
  {
    tzCode:'America/Indiana/Indianapolis',
    utc:'-05:00'
  },
  {
    tzCode:'America/Indiana/Marengo',
    utc:'-05:00'
  },
  {
    tzCode:'America/Indiana/Petersburg',
    utc:'-05:00'
  },
  {
    tzCode:'America/Indiana/Vevay',
    utc:'-05:00'
  },
  {
    tzCode:'America/Indiana/Vincennes',
    utc:'-05:00'
  },
  {
    tzCode:'America/Indiana/Winamac',
    utc:'-05:00'
  },
  {
    tzCode:'America/Iqaluit',
    utc:'-05:00'
  },
  {
    tzCode:'America/Jamaica',
    utc:'-05:00'
  },
  {
    tzCode:'America/Kentucky/Louisville',
    utc:'-05:00'
  },
  {
    tzCode:'America/Kentucky/Monticello',
    utc:'-05:00'
  },
  {
    tzCode:'America/Lima',
    utc:'-05:00'
  },
  {
    tzCode:'America/Nassau',
    utc:'-05:00'
  },
  {
    tzCode:'America/New_York',
    utc:'-05:00'
  },
  {
    tzCode:'America/Nipigon',
    utc:'-05:00'
  },
  {
    tzCode:'America/Panama',
    utc:'-05:00'
  },
  {
    tzCode:'America/Pangnirtung',
    utc:'-05:00'
  },
  {
    tzCode:'America/Port-au-Prince',
    utc:'-05:00'
  },
  {
    tzCode:'America/Rio_Branco',
    utc:'-05:00'
  },
  {
    tzCode:'America/Thunder_Bay',
    utc:'-05:00'
  },
  {
    tzCode:'America/Toronto',
    utc:'-05:00'
  },
  {
    tzCode:'America/AnguillaSandy Hill',
    utc:'-04:00'
  },
  {
    tzCode:'America/Antigua',
    utc:'-04:00'
  },
  {
    tzCode:'America/Aruba',
    utc:'-04:00'
  },
  {
    tzCode:'America/Asuncion',
    utc:'-04:00'
  },
  {
    tzCode:'America/Barbados',
    utc:'-04:00'
  },
  {
    tzCode:'America/Blanc-Sablon',
    utc:'-04:00'
  },
  {
    tzCode:'America/Boa_Vista',
    utc:'-04:00'
  },
  {
    tzCode:'America/Campo_Grande',
    utc:'-04:00'
  },
  {
    tzCode:'America/Caracas',
    utc:'-04:00'
  },
  {
    tzCode:'America/Cuiaba',
    utc:'-04:00'
  },
  {
    tzCode:'America/Curacao',
    utc:'-04:00'
  },
  {
    tzCode:'America/Dominica',
    utc:'-04:00'
  },
  {
    tzCode:'America/Glace_Bay',
    utc:'-04:00'
  },
  {
    tzCode:'America/Goose_Bay',
    utc:'-04:00'
  },
  {
    tzCode:'America/Grenada',
    utc:'-04:00'
  },
  {
    tzCode:'America/Guadeloupe',
    utc:'-04:00'
  },
  {
    tzCode:'America/Guyana',
    utc:'-04:00'
  },
  {
    tzCode:'America/Halifax',
    utc:'-04:00'
  },
  {
    tzCode:'America/Kralendijk',
    utc:'-04:00'
  },
  {
    tzCode:'America/La_Paz',
    utc:'-04:00'
  },
  {
    tzCode:'America/Lower_Princes',
    utc:'-04:00'
  },
  {
    tzCode:'America/Manaus',
    utc:'-04:00'
  },
  {
    tzCode:'America/Marigot',
    utc:'-04:00'
  },
  {
    tzCode:'America/Martinique',
    utc:'-04:00'
  },
  {
    tzCode:'America/Moncton',
    utc:'-04:00'
  },
  {
    tzCode:'America/Montserrat',
    utc:'-04:00'
  },
  {
    tzCode:'America/Porto_Velho',
    utc:'-04:00'
  },
  {
    tzCode:'America/Port_of_Spain',
    utc:'-04:00'
  },
  {
    tzCode:'America/Puerto_Rico',
    utc:'-04:00'
  },
  {
    tzCode:'America/Santiago',
    utc:'-04:00'
  },
  {
    tzCode:'America/Santo_Domingo',
    utc:'-04:00'
  },
  {
    tzCode:'America/St_Barthelemy',
    utc:'-04:00'
  },
  {
    tzCode:'America/St_Kitts',
    utc:'-04:00'
  },
  {
    tzCode:'America/St_Lucia',
    utc:'-04:00'
  },
  {
    tzCode:'America/St_Thomas',
    utc:'-04:00'
  },
  {
    tzCode:'America/St_Vincent',
    utc:'-04:00'
  },
  {
    tzCode:'America/Thule',
    utc:'-04:00'
  },
  {
    tzCode:'America/Tortola',
    utc:'-04:00'
  },
  {
    tzCode:'Atlantic/Bermuda',
    utc:'-04:00'
  },
  {
    tzCode:'America/St_Johns',
    utc:'-03:30'
  },
  {
    tzCode:'America/Araguaina',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/Buenos_Aires',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/Catamarca',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/Cordoba',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/Jujuy',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/La_Rioja',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/Mendoza',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/Rio_Gallegos',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/Salta',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/San_Juan',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/San_Luis',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/Tucuman',
    utc:'-03:00'
  },
  {
    tzCode:'America/Argentina/Ushuaia',
    utc:'-03:00'
  },
  {
    tzCode:'America/Bahia',
    utc:'-03:00'
  },
  {
    tzCode:'America/Belem',
    utc:'-03:00'
  },
  {
    tzCode:'America/Cayenne',
    utc:'-03:00'
  },
  {
    tzCode:'America/Fortaleza',
    utc:'-03:00'
  },
  {
    tzCode:'America/Godthab',
    utc:'-03:00'
  },
  {
    tzCode:'America/Maceio',
    utc:'-03:00'
  },
  {
    tzCode:'America/Miquelon',
    utc:'-03:00'
  },
  {
    tzCode:'America/Montevideo',
    utc:'-03:00'
  },
  {
    tzCode:'America/Paramaribo',
    utc:'-03:00'
  },
  {
    tzCode:'America/Punta_Arenas',
    utc:'-03:00'
  },
  {
    tzCode:'America/Recife',
    utc:'-03:00'
  },
  {
    tzCode:'America/Santarem',
    utc:'-03:00'
  },
  {
    tzCode:'America/Sao_Paulo',
    utc:'-03:00'
  },
  {
    tzCode:'Antarctica/Palmer',
    utc:'-03:00'
  },
  {
    tzCode:'Antarctica/Rothera',
    utc:'-03:00'
  },
  {
    tzCode:'Atlantic/Stanley',
    utc:'-03:00'
  },
  {
    tzCode:'America/Noronha',
    utc:'-02:00'
  },
  {
    tzCode:'Atlantic/South_Georgia',
    utc:'-02:00'
  },
  {
    tzCode:'America/Scoresbysund',
    utc:'-01:00'
  },
  {
    tzCode:'Atlantic/Azores',
    utc:'-01:00'
  },
  {
    tzCode:'Atlantic/Cape_Verde',
    utc:'-01:00'
  },
  {
    tzCode:'Africa/Abidjan',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Accra',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Bamako',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Banjul',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Bissau',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Casablanca',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Conakry',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Dakar',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/El_Aaiun',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Freetown',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Lome',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Monrovia',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Nouakchott',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Ouagadougou',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Sao_Tome',
    utc:'+00:00'
  },
  {
    tzCode:'America/Danmarkshavn',
    utc:'+00:00'
  },
  {
    tzCode:'Antarctica/Troll',
    utc:'+00:00'
  },
  {
    tzCode:'Atlantic/Canary',
    utc:'+00:00'
  },
  {
    tzCode:'Atlantic/Faroe',
    utc:'+00:00'
  },
  {
    tzCode:'Atlantic/Madeira',
    utc:'+00:00'
  },
  {
    tzCode:'Atlantic/Reykjavik',
    utc:'+00:00'
  },
  {
    tzCode:'Atlantic/St_Helena',
    utc:'+00:00'
  },
  {
    tzCode:'Europe/Dublin',
    utc:'+00:00'
  },
  {
    tzCode:'Europe/Guernsey',
    utc:'+00:00'
  },
  {
    tzCode:'Europe/Isle_of_Man',
    utc:'+00:00'
  },
  {
    tzCode:'Europe/Jersey',
    utc:'+00:00'
  },
  {
    tzCode:'Europe/Lisbon',
    utc:'+00:00'
  },
  {
    tzCode:'Europe/London',
    utc:'+00:00'
  },
  {
    tzCode:'Africa/Algiers',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Bangui',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Brazzaville',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Ceuta',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Douala',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Kinshasa',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Lagos',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Libreville',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Luanda',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Malabo',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Ndjamena',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Niamey',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Porto-Novo',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Tunis',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Windhoek',
    utc:'+01:00'
  },
  {
    tzCode:'Arctic/Longyearbyen',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Amsterdam',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Andorra',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Belgrade',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Berlin',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Bratislava',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Brussels',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Budapest',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Copenhagen',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Gibraltar',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Ljubljana',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Luxembourg',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Madrid',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Malta',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Monaco',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Oslo',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Paris',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Podgorica',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Prague',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Rome',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/San_Marino',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Sarajevo',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Skopje',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Stockholm',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Tirane',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Vaduz',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Vatican',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Vienna',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Warsaw',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Zagreb',
    utc:'+01:00'
  },
  {
    tzCode:'Europe/Zurich',
    utc:'+01:00'
  },
  {
    tzCode:'Africa/Blantyre',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Bujumbura',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Cairo',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Gaborone',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Harare',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Johannesburg',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Juba',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Khartoum',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Kigali',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Lubumbashi',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Lusaka',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Maputo',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Maseru',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Mbabane',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Tripoli',
    utc:'+02:00'
  },
  {
    tzCode:'Asia/Amman',
    utc:'+02:00'
  },
  {
    tzCode:'Asia/Beirut',
    utc:'+02:00'
  },
  {
    tzCode:'Asia/Damascus',
    utc:'+02:00'
  },
  {
    tzCode:'Asia/Famagusta',
    utc:'+02:00'
  },
  {
    tzCode:'Asia/Gaza',
    utc:'+02:00'
  },
  {
    tzCode:'Asia/Hebron',
    utc:'+02:00'
  },
  {
    tzCode:'Asia/Jerusalem',
    utc:'+02:00'
  },
  {
    tzCode:'Asia/Nicosia',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Athens',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Bucharest',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Chisinau',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Helsinki',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Kaliningrad',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Kiev',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Mariehamn',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Riga',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Sofia',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Tallinn',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Uzhgorod',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Vilnius',
    utc:'+02:00'
  },
  {
    tzCode:'Europe/Zaporozhye',
    utc:'+02:00'
  },
  {
    tzCode:'Africa/Addis_Ababa',
    utc:'+03:00'
  },
  {
    tzCode:'Africa/Asmara',
    utc:'+03:00'
  },
  {
    tzCode:'Africa/Dar_es_Salaam',
    utc:'+03:00'
  },
  {
    tzCode:'Africa/Djibouti',
    utc:'+03:00'
  },
  {
    tzCode:'Africa/Kampala',
    utc:'+03:00'
  },
  {
    tzCode:'Africa/Mogadishu',
    utc:'+03:00'
  },
  {
    tzCode:'Africa/Nairobi',
    utc:'+03:00'
  },
  {
    tzCode:'Antarctica/Syowa',
    utc:'+03:00'
  },
  {
    tzCode:'Asia/Aden',
    utc:'+03:00'
  },
  {
    tzCode:'Asia/Baghdad',
    utc:'+03:00'
  },
  {
    tzCode:'Asia/Bahrain',
    utc:'+03:00'
  },
  {
    tzCode:'Asia/Kuwait',
    utc:'+03:00'
  },
  {
    tzCode:'Asia/Qatar',
    utc:'+03:00'
  },
  {
    tzCode:'Asia/Riyadh',
    utc:'+03:00'
  },
  {
    tzCode:'Europe/Istanbul',
    utc:'+03:00'
  },
  {
    tzCode:'Europe/Kirov',
    utc:'+03:00'
  },
  {
    tzCode:'Europe/Minsk',
    utc:'+03:00'
  },
  {
    tzCode:'Europe/Moscow',
    utc:'+03:00'
  },
  {
    tzCode:'Europe/Simferopol',
    utc:'+03:00'
  },
  {
    tzCode:'Europe/Volgograd',
    utc:'+03:00'
  },
  {
    tzCode:'Indian/Antananarivo',
    utc:'+03:00'
  },
  {
    tzCode:'Indian/Comoro',
    utc:'+03:00'
  },
  {
    tzCode:'Indian/Mayotte',
    utc:'+03:00'
  },
  {
    tzCode:'Asia/Tehran',
    utc:'+03:30'
  },
  {
    tzCode:'Asia/Baku',
    utc:'+04:00'
  },
  {
    tzCode:'Asia/Dubai',
    utc:'+04:00'
  },
  {
    tzCode:'Asia/Muscat',
    utc:'+04:00'
  },
  {
    tzCode:'Asia/Tbilisi',
    utc:'+04:00'
  },
  {
    tzCode:'Asia/Yerevan',
    utc:'+04:00'
  },
  {
    tzCode:'Europe/Astrakhan',
    utc:'+04:00'
  },
  {
    tzCode:'Europe/Samara',
    utc:'+04:00'
  },
  {
    tzCode:'Europe/Saratov',
    utc:'+04:00'
  },
  {
    tzCode:'Europe/Ulyanovsk',
    utc:'+04:00'
  },
  {
    tzCode:'Indian/Mahe',
    utc:'+04:00'
  },
  {
    tzCode:'Indian/Mauritius',
    utc:'+04:00'
  },
  {
    tzCode:'Indian/Reunion',
    utc:'+04:00'
  },
  {
    tzCode:'Asia/Kabul',
    utc:'+04:30'
  },
  {
    tzCode:'Antarctica/Mawson',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Aqtau',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Aqtobe',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Ashgabat',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Atyrau',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Dushanbe',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Karachi',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Oral',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Qyzylorda',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Samarkand',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Tashkent',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Yekaterinburg',
    utc:'+05:00'
  },
  {
    tzCode:'Indian/Kerguelen',
    utc:'+05:00'
  },
  {
    tzCode:'Indian/Maldives',
    utc:'+05:00'
  },
  {
    tzCode:'Asia/Colombo',
    utc:'+05:30'
  },
  {
    tzCode:'Asia/Kolkata',
    utc:'+05:30'
  },
  {
    tzCode:'Asia/Kathmandu',
    utc:'+05:45'
  },
  {
    tzCode:'Antarctica/Vostok',
    utc:'+06:00'
  },
  {
    tzCode:'Asia/Almaty',
    utc:'+06:00'
  },
  {
    tzCode:'Asia/Bishkek',
    utc:'+06:00'
  },
  {
    tzCode:'Asia/Dhaka',
    utc:'+06:00'
  },
  {
    tzCode:'Asia/Omsk',
    utc:'+06:00'
  },
  {
    tzCode:'Asia/Qostanay',
    utc:'+06:00'
  },
  {
    tzCode:'Asia/Thimphu',
    utc:'+06:00'
  },
  {
    tzCode:'Asia/Urumqi',
    utc:'+06:00'
  },
  {
    tzCode:'Indian/Chagos',
    utc:'+06:00'
  },
  {
    tzCode:'Asia/Yangon',
    utc:'+06:30'
  },
  {
    tzCode:'Indian/Cocos',
    utc:'+06:30'
  },
  {
    tzCode:'Antarctica/Davis',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Bangkok',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Barnaul',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Hovd',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Ho_Chi_Minh',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Jakarta',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Krasnoyarsk',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Novokuznetsk',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Novosibirsk',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Phnom_Penh',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Pontianak',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Tomsk',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Vientiane',
    utc:'+07:00'
  },
  {
    tzCode:'Indian/Christmas',
    utc:'+07:00'
  },
  {
    tzCode:'Asia/Brunei',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Choibalsan',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Hong_Kong',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Irkutsk',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Kuala_Lumpur',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Kuching',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Macau',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Makassar',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Manila',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Shanghai',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Singapore',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Taipei',
    utc:'+08:00'
  },
  {
    tzCode:'Asia/Ulaanbaatar',
    utc:'+08:00'
  },
  {
    tzCode:'Australia/Perth',
    utc:'+08:00'
  },
  {
    tzCode:'Australia/Eucla',
    utc:'+08:45'
  },
  {
    tzCode:'Asia/Chita',
    utc:'+09:00'
  },
  {
    tzCode:'Asia/Dili',
    utc:'+09:00'
  },
  {
    tzCode:'Asia/Jayapura',
    utc:'+09:00'
  },
  {
    tzCode:'Asia/Khandyga',
    utc:'+09:00'
  },
  {
    tzCode:'Asia/Pyongyang',
    utc:'+09:00'
  },
  {
    tzCode:'Asia/Seoul',
    utc:'+09:00'
  },
  {
    tzCode:'Asia/Tokyo',
    utc:'+09:00'
  },
  {
    tzCode:'Asia/Yakutsk',
    utc:'+09:00'
  },
  {
    tzCode:'Pacific/Palau',
    utc:'+09:00'
  },
  {
    tzCode:'Australia/Adelaide',
    utc:'+09:30'
  },
  {
    tzCode:'Australia/Broken_Hill',
    utc:'+09:30'
  },
  {
    tzCode:'Australia/Darwin',
    utc:'+09:30'
  },
  {
    tzCode:'Antarctica/DumontDUrville',
    utc:'+10:00'
  },
  {
    tzCode:'Antarctica/Macquarie',
    utc:'+10:00'
  },
  {
    tzCode:'Asia/Ust-Nera',
    utc:'+10:00'
  },
  {
    tzCode:'Asia/Vladivostok',
    utc:'+10:00'
  },
  {
    tzCode:'Australia/Brisbane',
    utc:'+10:00'
  },
  {
    tzCode:'Australia/Currie',
    utc:'+10:00'
  },
  {
    tzCode:'Australia/Hobart',
    utc:'+10:00'
  },
  {
    tzCode:'Australia/Lindeman',
    utc:'+10:00'
  },
  {
    tzCode:'Australia/Melbourne',
    utc:'+10:00'
  },
  {
    tzCode:'Australia/Sydney',
    utc:'+10:00'
  },
  {
    tzCode:'Pacific/Chuuk',
    utc:'+10:00'
  },
  {
    tzCode:'Pacific/GuamVillage',
    utc:'+10:00'
  },
  {
    tzCode:'Pacific/Port_Moresby',
    utc:'+10:00'
  },
  {
    tzCode:'Pacific/Saipan',
    utc:'+10:00'
  },
  {
    tzCode:'Australia/Lord_Howe',
    utc:'+10:30'
  },
  {
    tzCode:'Antarctica/Casey',
    utc:'+11:00'
  },
  {
    tzCode:'Asia/Magadan',
    utc:'+11:00'
  },
  {
    tzCode:'Asia/Sakhalin',
    utc:'+11:00'
  },
  {
    tzCode:'Asia/Srednekolymsk',
    utc:'+11:00'
  },
  {
    tzCode:'Pacific/Bougainville',
    utc:'+11:00'
  },
  {
    tzCode:'Pacific/Efate',
    utc:'+11:00'
  },
  {
    tzCode:'Pacific/Guadalcanal',
    utc:'+11:00'
  },
  {
    tzCode:'Pacific/Kosrae',
    utc:'+11:00'
  },
  {
    tzCode:'Pacific/Norfolk',
    utc:'+11:00'
  },
  {
    tzCode:'Pacific/Noumea',
    utc:'+11:00'
  },
  {
    tzCode:'Pacific/Pohnpei',
    utc:'+11:00'
  },
  {
    tzCode:'Antarctica/McMurdo',
    utc:'+12:00'
  },
  {
    tzCode:'Asia/Anadyr',
    utc:'+12:00'
  },
  {
    tzCode:'Asia/Kamchatka',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Auckland',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Fiji',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Funafuti',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Kwajalein',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Majuro',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Nauru',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Tarawa',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Wake',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Wallis',
    utc:'+12:00'
  },
  {
    tzCode:'Pacific/Chatham',
    utc:'+12:45'
  },
  {
    tzCode:'Pacific/Apia',
    utc:'+13:00'
  },
  {
    tzCode:'Pacific/Enderbury',
    utc:'+13:00'
  },
  {
    tzCode:'Pacific/Fakaofo',
    utc:'+13:00'
  },
  {
    tzCode:'Pacific/Tongatapu',
    utc:'+13:00'
  },
  {
    tzCode:'Pacific/Kiritimati',
    utc:'+14:00'
  }
];