/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_databusbridge_free(a: number): void;
export function databusbridge_new(a: number, b: number, c: number, d: number): number;
export function databusbridge_init(a: number): number;
export function databusbridge_delete_cache(a: number, b: number, c: number): number;
export function databusbridge_get_datasheet_pack(a: number, b: number, c: number): number;
export function databusbridge_json0_create(a: number, b: number, c: number, d: number): void;
export function databusbridge_json0_apply(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function databusbridge_json0_transform(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function databusbridge_json0_transform_x(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function databusbridge_json0_invert(a: number, b: number, c: number, d: number): void;
export function databusbridge_json0_compose(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function json0_seri(a: number): void;
export function json0_inverse(a: number, b: number): void;
export function action_set_cell(a: number, b: number, c: number): void;
export function get_records(a: number, b: number): number;
export function action_add_record(a: number, b: number, c: number): void;
export function add_tn(a: number, b: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function wasm_bindgen__convert__closures__invoke1_mut__h1c96eaa25d150746(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__h4e68db465de2e92e(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__haae58e6881709f81(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf88c8e3624339deb(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h6f2d41a93fab5bb6(a: number, b: number, c: number, d: number): void;
