/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Robot run actions
*/
export class ActionExecutionVO {
    /**
    * Robot run action id
    */
    'actionId'?: string;
    /**
    * Robot run action type id
    */
    'actionTypeId'?: string;
    /**
    * Robot run success
    */
    'success'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "actionId",
            "baseName": "actionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "actionTypeId",
            "baseName": "actionTypeId",
            "type": "string",
            "format": ""
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ActionExecutionVO.attributeTypeMap;
    }

    public constructor() {
    }
}

