/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetsAuditOpRo } from '../models/AssetsAuditOpRo';
import { HttpFile } from '../http/http';

/**
* Attachment manual review results request
*/
export class AssetsAuditRo {
    'assetlist'?: Array<AssetsAuditOpRo>;
    /**
    * audit user id
    */
    'auditorUserId': string;
    /**
    * audit user name
    */
    'auditorName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetlist",
            "baseName": "assetlist",
            "type": "Array<AssetsAuditOpRo>",
            "format": ""
        },
        {
            "name": "auditorUserId",
            "baseName": "auditorUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "auditorName",
            "baseName": "auditorName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetsAuditRo.attributeTypeMap;
    }

    public constructor() {
    }
}

