/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Attachment Request Parameters
*/
export class AttachUrlOpRo {
    /**
    * URL of uploaded file
    */
    'url': string;
    /**
    * Type (0: user profile 1: space logo 2: data table attachment)
    */
    'type': number;
    /**
    * Data meter node Id (data meter attachment must be transferred)
    */
    'nodeId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "nodeId",
            "baseName": "nodeId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AttachUrlOpRo.attributeTypeMap;
    }

    public constructor() {
    }
}

