/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActionSimpleVO } from '../models/ActionSimpleVO';
import { TriggerSimpleVO } from '../models/TriggerSimpleVO';
import { HttpFile } from '../http/http';

/**
* Automation Vo
*/
export class AutomationSimpleVO {
    /**
    * Robot id
    */
    'robotId'?: string;
    /**
    * Robot name
    */
    'name'?: string;
    /**
    * Robot description
    */
    'description'?: string;
    /**
    * Robot resource id
    */
    'resourceId'?: string;
    /**
    * Weather the robot is on use
    */
    'isActive'?: number;
    /**
    * Automation triggers list
    */
    'triggers'?: Array<TriggerSimpleVO>;
    /**
    * Automation actions list
    */
    'actions'?: Array<ActionSimpleVO>;
    /**
    * Automation run num is over limit
    */
    'isOverLimit'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "robotId",
            "baseName": "robotId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceId",
            "baseName": "resourceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "triggers",
            "baseName": "triggers",
            "type": "Array<TriggerSimpleVO>",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<ActionSimpleVO>",
            "format": ""
        },
        {
            "name": "isOverLimit",
            "baseName": "isOverLimit",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AutomationSimpleVO.attributeTypeMap;
    }

    public constructor() {
    }
}

