/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* ChatBot Enable RO
*/
export class ChatbotEnableRo {
    /**
    * Space ID
    */
    'spaceId': string;
    /**
    * Auth Token
    */
    'token': string;
    /**
    * Valid Date
    */
    'days'?: number;
    /**
    * Whether off
    */
    'isOff'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "spaceId",
            "baseName": "spaceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        },
        {
            "name": "days",
            "baseName": "days",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "isOff",
            "baseName": "isOff",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChatbotEnableRo.attributeTypeMap;
    }

    public constructor() {
    }
}

