/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Application version information
*/
export class ClientInfoVO {
    /**
    * Client language set globally by the user
    */
    'locale'?: string;
    /**
    * User information
    */
    'userInfo'?: string;
    /**
    * Novice guidance information
    */
    'wizards'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        },
        {
            "name": "userInfo",
            "baseName": "userInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "wizards",
            "baseName": "wizards",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientInfoVO.attributeTypeMap;
    }

    public constructor() {
    }
}

