/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Meta } from '../models/Meta';
import { HttpFile } from '../http/http';

export class DataSource {
    'type'?: string;
    'typeId'?: string;
    'meta'?: Meta;
    'words'?: number;
    'characters'?: number;
    'tokens'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeId",
            "baseName": "typeId",
            "type": "string",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "Meta",
            "format": ""
        },
        {
            "name": "words",
            "baseName": "words",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "characters",
            "baseName": "characters",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return DataSource.attributeTypeMap;
    }

    public constructor() {
    }
}

