/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* DingTalk ISV User Login Request Parameters
*/
export class DingTalkIsvUserLoginVo {
    /**
    * Space ID bound by the application
    */
    'bindSpaceId'?: string;
    /**
    * Need to modify the name
    */
    'shouldRename'?: boolean;
    /**
    * Default name
    */
    'defaultName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bindSpaceId",
            "baseName": "bindSpaceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "shouldRename",
            "baseName": "shouldRename",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "defaultName",
            "baseName": "defaultName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DingTalkIsvUserLoginVo.attributeTypeMap;
    }

    public constructor() {
    }
}

