/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* DingTalk--Get SKU page of internal products
*/
export class DingTalkInternalSkuPageRo {
    /**
    * Space ID
    */
    'spaceId': string;
    /**
    * Callback page
    */
    'callbackPage'?: string;
    /**
    * If this value is passed in, it will be pushed when the order message is pushed.
    */
    'extendParam'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "spaceId",
            "baseName": "spaceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "callbackPage",
            "baseName": "callbackPage",
            "type": "string",
            "format": ""
        },
        {
            "name": "extendParam",
            "baseName": "extendParam",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DingTalkInternalSkuPageRo.attributeTypeMap;
    }

    public constructor() {
    }
}

