/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* DingTalk Tenant Space Change Primary Administrator Request Parameters
*/
export class DingTalkTenantMainAdminChangeRo {
    /**
    * Space identification
    */
    'spaceId': string;
    /**
    * MemberID of the new master administrator
    */
    'memberId': number;
    /**
    * Third party organization ID
    */
    'corpId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "spaceId",
            "baseName": "spaceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "memberId",
            "baseName": "memberId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "corpId",
            "baseName": "corpId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DingTalkTenantMainAdminChangeRo.attributeTypeMap;
    }

    public constructor() {
    }
}

