/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* DingTalk ISV Application Administrator Platform Password free Login Request Parameters
*/
export class DingTalkIsvAminUserLoginRo {
    /**
    * Registration free authorization code
    */
    'code': string;
    /**
    * Enterprise ID
    */
    'corpId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "corpId",
            "baseName": "corpId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DingTalkIsvAminUserLoginRo.attributeTypeMap;
    }

    public constructor() {
    }
}

