/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Space } from '../models/Space';
import { HttpFile } from '../http/http';

/**
* Lark tenant information
*/
export class FeishuTenantDetailVO {
    /**
    * List of bound spaces
    */
    'spaces'?: Array<Space>;
    /**
    * Lark Enterprise ID
    */
    'tenantKey'?: string;
    /**
    * Lark Enterprise name
    */
    'tenantName'?: string;
    /**
    * Lark Enterprise avatar
    */
    'avatar'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "spaces",
            "baseName": "spaces",
            "type": "Array<Space>",
            "format": ""
        },
        {
            "name": "tenantKey",
            "baseName": "tenantKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "tenantName",
            "baseName": "tenantName",
            "type": "string",
            "format": ""
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FeishuTenantDetailVO.attributeTypeMap;
    }

    public constructor() {
    }
}

