/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FieldRole } from '../models/FieldRole';
import { FieldRoleMemberVo } from '../models/FieldRoleMemberVo';
import { FieldRoleSetting } from '../models/FieldRoleSetting';
import { HttpFile } from '../http/http';

/**
* Data Table Field Permission View
*/
export class FieldCollaboratorVO {
    /**
    * Whether to open
    */
    'enabled'?: boolean;
    /**
    * Role Member List
    */
    'members'?: Array<FieldRoleMemberVo>;
    /**
    * Role Org Unit List
    */
    'roles'?: Array<FieldRole>;
    'setting'?: FieldRoleSetting;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<FieldRoleMemberVo>",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<FieldRole>",
            "format": ""
        },
        {
            "name": "setting",
            "baseName": "setting",
            "type": "FieldRoleSetting",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FieldCollaboratorVO.attributeTypeMap;
    }

    public constructor() {
    }
}

