/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* space automation run information view
*/
export class InternalSpaceAutomationRunMessageV0 {
    /**
    * whether to allow over limiting
    */
    'allowRun'?: boolean;
    /**
    * Number of automation run
    */
    'automationRunNums'?: number;
    /**
    * the maximum automation run number for ai query(unit: int)
    */
    'maxAutomationRunNums'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allowRun",
            "baseName": "allowRun",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "automationRunNums",
            "baseName": "automationRunNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxAutomationRunNums",
            "baseName": "maxAutomationRunNums",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return InternalSpaceAutomationRunMessageV0.attributeTypeMap;
    }

    public constructor() {
    }
}

