/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* space usage information view
*/
export class InternalSpaceUsageVo {
    /**
    * The total number of rows in all tables of the space
    */
    'recordNums'?: number;
    /**
    * total album views
    */
    'galleryViewNums'?: number;
    /**
    * total kanban views
    */
    'kanbanViewNums'?: number;
    /**
    * total gantt views
    */
    'ganttViewNums'?: number;
    /**
    * total number of calendar views
    */
    'calendarViewNums'?: number;
    /**
    * Number of used credit
    */
    'usedCredit'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordNums",
            "baseName": "recordNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "galleryViewNums",
            "baseName": "galleryViewNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "kanbanViewNums",
            "baseName": "kanbanViewNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "ganttViewNums",
            "baseName": "ganttViewNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "calendarViewNums",
            "baseName": "calendarViewNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "usedCredit",
            "baseName": "usedCredit",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InternalSpaceUsageVo.attributeTypeMap;
    }

    public constructor() {
    }
}

