/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Invitation Information View
*/
export class InviteInfoVo {
    /**
    * Space ID
    */
    'spaceId'?: string;
    /**
    * Space name
    */
    'spaceName'?: string;
    /**
    * Invite Users
    */
    'inviter'?: string;
    /**
    * Invited Email
    */
    'inviteEmail'?: string;
    /**
    * Whether it is in login status
    */
    'isLogin'?: boolean;
    /**
    * Whether the invited mailbox has an account bound
    */
    'isBound'?: boolean;
    /**
    * Inviter\'s personal invitation code
    */
    'inviteCode'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "spaceId",
            "baseName": "spaceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "spaceName",
            "baseName": "spaceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "inviter",
            "baseName": "inviter",
            "type": "string",
            "format": ""
        },
        {
            "name": "inviteEmail",
            "baseName": "inviteEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "isLogin",
            "baseName": "isLogin",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isBound",
            "baseName": "isBound",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "inviteCode",
            "baseName": "inviteCode",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InviteInfoVo.attributeTypeMap;
    }

    public constructor() {
    }
}

