/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Intent } from '../models/Intent';
import { JSONObject } from '../models/JSONObject';
import { Node } from '../models/Node';
import { Space } from '../models/Space';
import { HttpFile } from '../http/http';

/**
* Notice content
*/
export class NotifyBody {
    /**
    * Send notification to users
    */
    'template'?: string;
    /**
    * Send notification to users
    */
    'title'?: string;
    'node'?: Node;
    'space'?: Space;
    'extras'?: JSONObject;
    'intent'?: Intent;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "template",
            "baseName": "template",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "node",
            "baseName": "node",
            "type": "Node",
            "format": ""
        },
        {
            "name": "space",
            "baseName": "space",
            "type": "Space",
            "format": ""
        },
        {
            "name": "extras",
            "baseName": "extras",
            "type": "JSONObject",
            "format": ""
        },
        {
            "name": "intent",
            "baseName": "intent",
            "type": "Intent",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NotifyBody.attributeTypeMap;
    }

    public constructor() {
    }
}

