/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Org Unit Request Parameters
*/
export class OrgUnitRo {
    /**
    * ID
    */
    'id': number;
    /**
    * Classification, only the specified type can be received, 1=department, 2=member
    */
    'type': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return OrgUnitRo.attributeTypeMap;
    }

    public constructor() {
    }
}

