/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Official account QR code vo
*/
export class QrCodeVo {
    /**
    * Unique identification
    */
    'mark'?: string;
    /**
    * QR Code Picture
    */
    'image'?: string;
    /**
    * The address of the QR code image after parsing, and the QR code image can be generated by yourself
    */
    'url'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mark",
            "baseName": "mark",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QrCodeVo.attributeTypeMap;
    }

    public constructor() {
    }
}

