/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RedirectViewServletContextServletRegistrationsValue {
    'mappings'?: Array<string>;
    'runAsRole'?: string;
    'initParameters'?: { [key: string]: string; };
    'name'?: string;
    'className'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mappings",
            "baseName": "mappings",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "runAsRole",
            "baseName": "runAsRole",
            "type": "string",
            "format": ""
        },
        {
            "name": "initParameters",
            "baseName": "initParameters",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "className",
            "baseName": "className",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RedirectViewServletContextServletRegistrationsValue.attributeTypeMap;
    }

    public constructor() {
    }
}

