/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Recycle Bin Node Information View
*/
export class RubbishNodeVo {
    /**
    * Node ID
    */
    'nodeId'?: string;
    /**
    * Node Name
    */
    'nodeName'?: string;
    /**
    * Node Type 0-ROOT（Root node） 1-folder（Folder） 2-file（Datasheet）
    */
    'type'?: number;
    /**
    * Space ID
    */
    'spaceId'?: string;
    /**
    * Node icon
    */
    'icon'?: string;
    /**
    * User uuid of the deleted user
    */
    'uuid'?: string;
    /**
    * Deleted by Member Name
    */
    'memberName'?: string;
    /**
    * Remover\'s avatar
    */
    'avatar'?: string;
    /**
    * Whether the user has modified the nickname
    */
    'isNickNameModified'?: boolean;
    /**
    * Whether the member has modified the nickname
    */
    'isMemberNameModified'?: boolean;
    /**
    * Delete time(millisecond)
    */
    'deletedAt'?: Date;
    /**
    * Delete Path
    */
    'delPath'?: string;
    /**
    * Days Remain
    */
    'remainDay'?: number;
    /**
    * default avatar color number
    */
    'avatarColor'?: number;
    /**
    * Nick Name
    */
    'nickName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nodeId",
            "baseName": "nodeId",
            "type": "string",
            "format": ""
        },
        {
            "name": "nodeName",
            "baseName": "nodeName",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "spaceId",
            "baseName": "spaceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "memberName",
            "baseName": "memberName",
            "type": "string",
            "format": ""
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "isNickNameModified",
            "baseName": "isNickNameModified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMemberNameModified",
            "baseName": "isMemberNameModified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deletedAt",
            "baseName": "deletedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "delPath",
            "baseName": "delPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "remainDay",
            "baseName": "remainDay",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "avatarColor",
            "baseName": "avatarColor",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "nickName",
            "baseName": "nickName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RubbishNodeVo.attributeTypeMap;
    }

    public constructor() {
    }
}

