/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Seat usage
*/
export class SeatUsage {
    'total'?: number;
    'chatBotCount'?: number;
    'memberCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "chatBotCount",
            "baseName": "chatBotCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "memberCount",
            "baseName": "memberCount",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return SeatUsage.attributeTypeMap;
    }

    public constructor() {
    }
}

