/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Mobile phone verification code verification request parameters
*/
export class SmsCodeValidateRo {
    /**
    * Area code
    */
    'areaCode': string;
    /**
    * Phone number
    */
    'phone': string;
    /**
    * Mobile phone verification code
    */
    'code': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "areaCode",
            "baseName": "areaCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SmsCodeValidateRo.attributeTypeMap;
    }

    public constructor() {
    }
}

