/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Mobile verification code request parameters
*/
export class SmsOpRo {
    /**
    * Area code
    */
    'areaCode': string;
    /**
    * cell-phone number
    */
    'phone': string;
    /**
    * SMS verification code type
    */
    'type': number;
    /**
    * Man machine verification, the front end obtains the value of get NVC Val function
    */
    'data'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "areaCode",
            "baseName": "areaCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SmsOpRo.attributeTypeMap;
    }

    public constructor() {
    }
}

