/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Space Subscribe Info
*/
export class SpaceSubscribeVo {
    /**
    * version
    */
    'version'?: string;
    /**
    * produce name
    */
    'product'?: string;
    /**
    * whether on trial
    */
    'onTrial'?: boolean;
    'billingMode'?: string;
    'recurringInterval'?: string;
    /**
    * plan name
    */
    'plan'?: string;
    /**
    * added plan names
    */
    'addOnPlans'?: Array<string>;
    'expireAt'?: number;
    /**
    * subscription expiration time. if free, it is null.
    */
    'deadline'?: string;
    /**
    * seat(unit: people)
    */
    'maxSeats'?: number;
    /**
    * capacity(unit: MB)
    */
    'maxCapacitySizeInBytes'?: number;
    /**
    * sheet number(unit: table)
    */
    'maxSheetNums'?: number;
    /**
    * max rows per sheet(unit: row)
    */
    'maxRowsPerSheet'?: number;
    /**
    * max rows in space(unit: row)
    */
    'maxRowsInSpace'?: number;
    /**
    * api usage limit(unit: count)
    */
    'maxApiCall'?: number;
    /**
    * admin nums(unit: person)
    */
    'maxAdminNums'?: number;
    /**
    * days of storage in trash(unit: day)
    */
    'maxRemainTrashDays'?: number;
    /**
    * max gallery views in space(unit: view)
    */
    'maxGalleryViewsInSpace'?: number;
    /**
    * max kanban views in space(unit: view)
    */
    'maxKanbanViewsInSpace'?: number;
    /**
    * max form views in space(unit: form)
    */
    'maxFormViewsInSpace'?: number;
    /**
    * max gantt views in space(unit: view)
    */
    'maxGanttViewsInSpace'?: number;
    /**
    * max calendar views in space(unit: view)
    */
    'maxCalendarViewsInSpace'?: number;
    /**
    * max field permission nums(unit: unit)
    */
    'fieldPermissionNums'?: number;
    /**
    * max node permission nums(unit: unit)
    */
    'nodePermissionNums'?: number;
    /**
    * number of days the time machine retains data(unit: day)
    */
    'maxRemainTimeMachineDays'?: number;
    /**
    * whether it can be integrated dingtalk
    */
    'integrationDingtalk'?: boolean;
    /**
    * whether it can be integrated feishu
    */
    'integrationFeishu'?: boolean;
    /**
    * whether it can be integrated wecom
    */
    'integrationWeCom'?: boolean;
    /**
    * whether it can be office preview
    */
    'integrationOfficePreview'?: boolean;
    /**
    * whether it has rainbow label
    */
    'rainbowLabel'?: boolean;
    /**
    * whether it has global watermark
    */
    'watermark'?: boolean;
    /**
    * max days of remain record activity (unit: day)
    */
    'maxRemainRecordActivityDays'?: number;
    /**
    * whether space in the black space
    */
    'blackSpace'?: boolean;
    /**
    * Security Settings - ordinary members perform the invite operation
    */
    'securitySettingInviteMember'?: boolean;
    /**
    * Security Settings - off station users apply to join the space
    */
    'securitySettingApplyJoinSpace'?: boolean;
    /**
    * Security Settings - create a public link
    */
    'securitySettingShare'?: boolean;
    /**
    * Security Settings - export datasheet
    */
    'securitySettingExport'?: boolean;
    /**
    * Security Settings - read only users download attachments
    */
    'securitySettingDownloadFile'?: boolean;
    /**
    * Security Settings - read only users copy data off site
    */
    'securitySettingCopyCellData'?: boolean;
    /**
    * Security Settings - display member\'s mobile phone number
    */
    'securitySettingMobile'?: boolean;
    /**
    * the maximum days for querying audit logs(unit: day)
    */
    'maxAuditQueryDays'?: number;
    /**
    * the maximum credit number for ai query(unit: int)
    */
    'maxMessageCredits'?: number;
    /**
    * the maximum automation count (unit: int)
    */
    'maxAutomationRunNums'?: number;
    /**
    * the maximum Widget count (unit: int)
    */
    'maxWidgetNums'?: number;
    /**
    * complimentary unexpired capacity(unit：byte)
    */
    'unExpireGiftCapacity'?: number;
    /**
    * capacity(unit：byte)
    */
    'subscriptionCapacity'?: number;
    /**
    * Security Settings - hidden concact
    */
    'securitySettingAddressListIsolation'?: boolean;
    /**
    * Security Settings - prohibit members manage files in the root directory
    */
    'securitySettingCatalogManagement'?: boolean;
    /**
    * max mirror nums(unit: mirror)
    */
    'maxMirrorNums'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "string",
            "format": ""
        },
        {
            "name": "onTrial",
            "baseName": "onTrial",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "billingMode",
            "baseName": "billingMode",
            "type": "string",
            "format": ""
        },
        {
            "name": "recurringInterval",
            "baseName": "recurringInterval",
            "type": "string",
            "format": ""
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "string",
            "format": ""
        },
        {
            "name": "addOnPlans",
            "baseName": "addOnPlans",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "expireAt",
            "baseName": "expireAt",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "string",
            "format": "date"
        },
        {
            "name": "maxSeats",
            "baseName": "maxSeats",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxCapacitySizeInBytes",
            "baseName": "maxCapacitySizeInBytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxSheetNums",
            "baseName": "maxSheetNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRowsPerSheet",
            "baseName": "maxRowsPerSheet",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRowsInSpace",
            "baseName": "maxRowsInSpace",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxApiCall",
            "baseName": "maxApiCall",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxAdminNums",
            "baseName": "maxAdminNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRemainTrashDays",
            "baseName": "maxRemainTrashDays",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxGalleryViewsInSpace",
            "baseName": "maxGalleryViewsInSpace",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxKanbanViewsInSpace",
            "baseName": "maxKanbanViewsInSpace",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxFormViewsInSpace",
            "baseName": "maxFormViewsInSpace",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxGanttViewsInSpace",
            "baseName": "maxGanttViewsInSpace",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxCalendarViewsInSpace",
            "baseName": "maxCalendarViewsInSpace",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "fieldPermissionNums",
            "baseName": "fieldPermissionNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "nodePermissionNums",
            "baseName": "nodePermissionNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRemainTimeMachineDays",
            "baseName": "maxRemainTimeMachineDays",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "integrationDingtalk",
            "baseName": "integrationDingtalk",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "integrationFeishu",
            "baseName": "integrationFeishu",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "integrationWeCom",
            "baseName": "integrationWeCom",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "integrationOfficePreview",
            "baseName": "integrationOfficePreview",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rainbowLabel",
            "baseName": "rainbowLabel",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "watermark",
            "baseName": "watermark",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maxRemainRecordActivityDays",
            "baseName": "maxRemainRecordActivityDays",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "blackSpace",
            "baseName": "blackSpace",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "securitySettingInviteMember",
            "baseName": "securitySettingInviteMember",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "securitySettingApplyJoinSpace",
            "baseName": "securitySettingApplyJoinSpace",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "securitySettingShare",
            "baseName": "securitySettingShare",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "securitySettingExport",
            "baseName": "securitySettingExport",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "securitySettingDownloadFile",
            "baseName": "securitySettingDownloadFile",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "securitySettingCopyCellData",
            "baseName": "securitySettingCopyCellData",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "securitySettingMobile",
            "baseName": "securitySettingMobile",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maxAuditQueryDays",
            "baseName": "maxAuditQueryDays",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxMessageCredits",
            "baseName": "maxMessageCredits",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxAutomationRunNums",
            "baseName": "maxAutomationRunNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxWidgetNums",
            "baseName": "maxWidgetNums",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "unExpireGiftCapacity",
            "baseName": "unExpireGiftCapacity",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "subscriptionCapacity",
            "baseName": "subscriptionCapacity",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "securitySettingAddressListIsolation",
            "baseName": "securitySettingAddressListIsolation",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "securitySettingCatalogManagement",
            "baseName": "securitySettingCatalogManagement",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maxMirrorNums",
            "baseName": "maxMirrorNums",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return SpaceSubscribeVo.attributeTypeMap;
    }

    public constructor() {
    }
}

