/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpaceSocialConfig } from '../models/SpaceSocialConfig';
import { HttpFile } from '../http/http';

/**
* Space List View
*/
export class SpaceVO {
    /**
    * Space ID
    */
    'spaceId'?: string;
    /**
    * Name
    */
    'name'?: string;
    /**
    * Icon
    */
    'logo'?: string;
    /**
    * Whether there are red dots
    */
    'point'?: boolean;
    /**
    * Whether it is the main administrator of the space
    */
    'admin'?: boolean;
    /**
    * Whether it is in pre deletion status
    */
    'preDeleted'?: boolean;
    /**
    * Maximum total number of subscription plan members
    */
    'maxSeat'?: number;
    /**
    * Space domain name
    */
    'spaceDomain'?: string;
    'social'?: SpaceSocialConfig;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "spaceId",
            "baseName": "spaceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "string",
            "format": ""
        },
        {
            "name": "point",
            "baseName": "point",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "admin",
            "baseName": "admin",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "preDeleted",
            "baseName": "preDeleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maxSeat",
            "baseName": "maxSeat",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "spaceDomain",
            "baseName": "spaceDomain",
            "type": "string",
            "format": ""
        },
        {
            "name": "social",
            "baseName": "social",
            "type": "SpaceSocialConfig",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SpaceVO.attributeTypeMap;
    }

    public constructor() {
    }
}

