/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Request parameters for space joining application processing
*/
export class SpaceJoinProcessRo {
    /**
    * Notification ID
    */
    'notifyId': number;
    /**
    * Agree or not
    */
    'agree': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "notifyId",
            "baseName": "notifyId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "agree",
            "baseName": "agree",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SpaceJoinProcessRo.attributeTypeMap;
    }

    public constructor() {
    }
}

