/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Third party integrated binding information of the space
*/
export class SpaceSocialConfig {
    /**
    * Whether the third party platform binding is enabled for the space
    */
    'enabled'?: boolean;
    /**
    * Third party platform type（1: WeCom, 2: DingTalk, 3: Lark）
    */
    'platform'?: number;
    /**
    * App ID
    */
    'appId'?: string;
    /**
    * Application Type(1: Enterprise self built application, 2: Independent service provider)
    */
    'appType'?: number;
    /**
    * Authorization mode. 1: Enterprise authorization; 2: Member Authorization
    */
    'authMode'?: number;
    /**
    * Whether the address book is being synchronized
    */
    'contactSyncing'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "appId",
            "baseName": "appId",
            "type": "string",
            "format": ""
        },
        {
            "name": "appType",
            "baseName": "appType",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "authMode",
            "baseName": "authMode",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "contactSyncing",
            "baseName": "contactSyncing",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SpaceSocialConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

