/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Template View
*/
export class TemplateVo {
    /**
    * Template ID
    */
    'templateId'?: string;
    /**
    * Template Name
    */
    'templateName'?: string;
    /**
    * Node Id of template mapping
    */
    'nodeId'?: string;
    /**
    * Node Type
    */
    'nodeType'?: number;
    /**
    * Cover
    */
    'cover'?: string;
    /**
    * Describe
    */
    'description'?: string;
    /**
    * Creator user ID (the actual return is uuid)
    */
    'userId'?: string;
    /**
    * Creator User UUID
    */
    'uuid'?: string;
    /**
    * Creator\'s avatar
    */
    'avatar'?: string;
    /**
    * Creator nickname
    */
    'nickName'?: string;
    /**
    * Whether the user has modified the nickname
    */
    'isNickNameModified'?: boolean;
    /**
    * Template label
    */
    'tags'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "templateId",
            "baseName": "templateId",
            "type": "string",
            "format": ""
        },
        {
            "name": "templateName",
            "baseName": "templateName",
            "type": "string",
            "format": ""
        },
        {
            "name": "nodeId",
            "baseName": "nodeId",
            "type": "string",
            "format": ""
        },
        {
            "name": "nodeType",
            "baseName": "nodeType",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "cover",
            "baseName": "cover",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "nickName",
            "baseName": "nickName",
            "type": "string",
            "format": ""
        },
        {
            "name": "isNickNameModified",
            "baseName": "isNickNameModified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TemplateVo.attributeTypeMap;
    }

    public constructor() {
    }
}

