/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Automation triggers list
*/
export class TriggerSimpleVO {
    /**
    * Trigger id
    */
    'triggerId'?: string;
    /**
    * Trigger type id
    */
    'triggerTypeId'?: string;
    /**
    * Trigger type id
    */
    'prevTriggerId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "triggerId",
            "baseName": "triggerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "triggerTypeId",
            "baseName": "triggerTypeId",
            "type": "string",
            "format": ""
        },
        {
            "name": "prevTriggerId",
            "baseName": "prevTriggerId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TriggerSimpleVO.attributeTypeMap;
    }

    public constructor() {
    }
}

