/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UnionEmpMapVo {
    'userid'?: string;
    'corpId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userid",
            "baseName": "userid",
            "type": "string",
            "format": ""
        },
        {
            "name": "corpId",
            "baseName": "corpId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UnionEmpMapVo.attributeTypeMap;
    }

    public constructor() {
    }
}

