/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Department Unit View
*/
export class UnitTeamVo {
    /**
    * Org Unit ID
    */
    'unitId'?: number;
    /**
    * Group ID
    */
    'teamId'?: number;
    /**
    * Group name
    */
    'teamName'?: string;
    /**
    * Department name (not highlighted)
    */
    'originName'?: string;
    /**
    * Number of members
    */
    'memberCount'?: number;
    /**
    * Whether there are sub departments and members
    */
    'hasChildren'?: boolean;
    /**
    * Whether there are sub departments
    */
    'hasChildrenTeam'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "teamName",
            "baseName": "teamName",
            "type": "string",
            "format": ""
        },
        {
            "name": "originName",
            "baseName": "originName",
            "type": "string",
            "format": ""
        },
        {
            "name": "memberCount",
            "baseName": "memberCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "hasChildren",
            "baseName": "hasChildren",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasChildrenTeam",
            "baseName": "hasChildrenTeam",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UnitTeamVo.attributeTypeMap;
    }

    public constructor() {
    }
}

