/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Internal-modify role ro
*/
export class UpdateUnitRoleRo {
    /**
    * Role name
    */
    'roleName'?: string;
    /**
    * Role position
    */
    'position'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "roleName",
            "baseName": "roleName",
            "type": "string",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return UpdateUnitRoleRo.attributeTypeMap;
    }

    public constructor() {
    }
}

