/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Update administrator request parameters
*/
export class UpdateSpaceRoleRo {
    /**
    * Role ID
    */
    'id': number;
    /**
    * Select Member ID
    */
    'memberId': number;
    /**
    * Operation resource set, no sorting, automatic verification
    */
    'resourceCodes': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "memberId",
            "baseName": "memberId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "resourceCodes",
            "baseName": "resourceCodes",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateSpaceRoleRo.attributeTypeMap;
    }

    public constructor() {
    }
}

