/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Update Trigger RO
*/
export class UpdateTriggerRO {
    /**
    * robot id
    */
    'robotId': string;
    /**
    * trigger input
    */
    'input'?: any;
    /**
    * related resource id
    */
    'relatedResourceId'?: string;
    /**
    * prev trigger id
    */
    'prevTriggerId'?: string;
    /**
    * trigger type id
    */
    'triggerTypeId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "robotId",
            "baseName": "robotId",
            "type": "string",
            "format": ""
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "any",
            "format": ""
        },
        {
            "name": "relatedResourceId",
            "baseName": "relatedResourceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "prevTriggerId",
            "baseName": "prevTriggerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "triggerTypeId",
            "baseName": "triggerTypeId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateTriggerRO.attributeTypeMap;
    }

    public constructor() {
    }
}

