/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Code V active view
*/
export class VCodeActivityVo {
    /**
    * Activity ID
    */
    'activityId'?: number;
    /**
    * Activity Name
    */
    'name'?: string;
    /**
    * Scene Values
    */
    'scene'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "activityId",
            "baseName": "activityId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "scene",
            "baseName": "scene",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VCodeActivityVo.attributeTypeMap;
    }

    public constructor() {
    }
}

