/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* V code creation request parameters
*/
export class VCodeCreateRo {
    /**
    * Create quantity
    */
    'count': number;
    /**
    * Type of V code (0: official invitation code; 2: exchange code)
    */
    'type': number;
    /**
    * Activity ID
    */
    'activityId': number;
    /**
    * Redemption template ID (required when the type is redemption code)
    */
    'templateId'?: number;
    /**
    * The total number of times a single V code can be used (- 1 represents an unlimited number of times, 1 by default)
    */
    'availableTimes'?: number;
    /**
    * Single V code can only be used by one person. The default is 1 time
    */
    'limitTimes'?: number;
    /**
    * Expiration time
    */
    'expireTime'?: Date;
    /**
    * Specify the mobile phone number of the user\'s account
    */
    'mobile'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "activityId",
            "baseName": "activityId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "templateId",
            "baseName": "templateId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "availableTimes",
            "baseName": "availableTimes",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "limitTimes",
            "baseName": "limitTimes",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "expireTime",
            "baseName": "expireTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "mobile",
            "baseName": "mobile",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VCodeCreateRo.attributeTypeMap;
    }

    public constructor() {
    }
}

