/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Get the authorization link for installing vika
*/
export class WeComIsvRegisterInstallSelfUrlVo {
    /**
    * Authorization link
    */
    'url': string;
    /**
    * Random status code in authorization link
    */
    'state': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WeComIsvRegisterInstallSelfUrlVo.attributeTypeMap;
    }

    public constructor() {
    }
}

