/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* widget release request
*/
export class WidgetPackageReleaseV2Ro {
    /**
    * icon file token
    */
    'iconToken'?: string;
    /**
    * cover file token
    */
    'coverToken'?: string;
    /**
    * author
    */
    'authorName'?: string;
    /**
    * author icon file token
    */
    'authorIconToken'?: string;
    /**
    * author email
    */
    'authorEmail'?: string;
    /**
    * author website
    */
    'authorLink'?: string;
    /**
    * widget description
    */
    'description'?: string;
    /**
    * release code link
    */
    'releaseCodeBundleToken'?: string;
    /**
    * source code link
    */
    'sourceCodeBundleToken'?: string;
    /**
    * the source code\'s secret key
    */
    'secretKey'?: string;
    /**
    * widget package\'s id
    */
    'packageId': string;
    /**
    * version
    */
    'version': string;
    /**
    * space id
    */
    'spaceId': string;
    /**
    * widget name
    */
    'name'?: string;
    /**
    * release note
    */
    'releaseNote'?: string;
    /**
    * is sandbox
    */
    'sandbox'?: boolean;
    /**
    * install environment
    */
    'installEnv'?: Array<string>;
    /**
    * runtime environment
    */
    'runtimeEnv'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "iconToken",
            "baseName": "iconToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "coverToken",
            "baseName": "coverToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorName",
            "baseName": "authorName",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorIconToken",
            "baseName": "authorIconToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorEmail",
            "baseName": "authorEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorLink",
            "baseName": "authorLink",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "releaseCodeBundleToken",
            "baseName": "releaseCodeBundleToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceCodeBundleToken",
            "baseName": "sourceCodeBundleToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "secretKey",
            "baseName": "secretKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "packageId",
            "baseName": "packageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "spaceId",
            "baseName": "spaceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "releaseNote",
            "baseName": "releaseNote",
            "type": "string",
            "format": ""
        },
        {
            "name": "sandbox",
            "baseName": "sandbox",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "installEnv",
            "baseName": "installEnv",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "runtimeEnv",
            "baseName": "runtimeEnv",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WidgetPackageReleaseV2Ro.attributeTypeMap;
    }

    public constructor() {
    }
}

