/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Widget snapshot information
*/
export class WidgetSnapshot {
    /**
    * Widget Name
    */
    'widgetName'?: string;
    /**
    * Data source table ID
    */
    'datasheetId'?: string;
    /**
    * Storage configuration
    */
    'storage'?: { [key: string]: any; };
    /**
    * Data source reference source ID
    */
    'sourceId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "widgetName",
            "baseName": "widgetName",
            "type": "string",
            "format": ""
        },
        {
            "name": "datasheetId",
            "baseName": "datasheetId",
            "type": "string",
            "format": ""
        },
        {
            "name": "storage",
            "baseName": "storage",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "sourceId",
            "baseName": "sourceId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WidgetSnapshot.attributeTypeMap;
    }

    public constructor() {
    }
}

