/**
 * Api Document
 * Backend_Server Api Document
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Blocking of widget/Unsealing request parameters
*/
export class WidgetPackageBanRo {
    /**
    * Widget Package ID
    */
    'packageId': string;
    /**
    * Blocking: false, unblocking: true
    */
    'unban': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "packageId",
            "baseName": "packageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "unban",
            "baseName": "unban",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WidgetPackageBanRo.attributeTypeMap;
    }

    public constructor() {
    }
}

