/*
 * databus-server
 * databus-server APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apitable.databusclient.api;

import com.apitable.databusclient.ApiCallback;
import com.apitable.databusclient.ApiClient;
import com.apitable.databusclient.ApiException;
import com.apitable.databusclient.ApiResponse;
import com.apitable.databusclient.Configuration;
import com.apitable.databusclient.Pair;
import com.apitable.databusclient.ProgressRequestBody;
import com.apitable.databusclient.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.apitable.databusclient.model.ApiResponseAutomationRobotIntroductionSO;
import com.apitable.databusclient.model.ApiResponseAutomationSO;
import com.apitable.databusclient.model.ApiResponseEmptySO;
import com.apitable.databusclient.model.AutomationHistoryStatusRO;
import com.apitable.databusclient.model.AutomationRobotUpdateRO;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AutomationDaoApiApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AutomationDaoApiApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AutomationDaoApiApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for daoCreateAutomationRunHistory
     * @param robotId robot id (required)
     * @param body  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> create automation run history task success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoCreateAutomationRunHistoryCall(String robotId, Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/databus/dao/automations/{robot_id}/histories"
            .replace("{" + "robot_id" + "}", localVarApiClient.escapeString(robotId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call daoCreateAutomationRunHistoryValidateBeforeCall(String robotId, Object body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'robotId' is set
        if (robotId == null) {
            throw new ApiException("Missing the required parameter 'robotId' when calling daoCreateAutomationRunHistory(Async)");
        }

        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling daoCreateAutomationRunHistory(Async)");
        }

        return daoCreateAutomationRunHistoryCall(robotId, body, _callback);

    }

    /**
     * create automation run history task success
     * create automation run history task success
     * @param robotId robot id (required)
     * @param body  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> create automation run history task success </td><td>  -  </td></tr>
     </table>
     */
    public void daoCreateAutomationRunHistory(String robotId, Object body) throws ApiException {
        daoCreateAutomationRunHistoryWithHttpInfo(robotId, body);
    }

    /**
     * create automation run history task success
     * create automation run history task success
     * @param robotId robot id (required)
     * @param body  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> create automation run history task success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> daoCreateAutomationRunHistoryWithHttpInfo(String robotId, Object body) throws ApiException {
        okhttp3.Call localVarCall = daoCreateAutomationRunHistoryValidateBeforeCall(robotId, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * create automation run history task success (asynchronously)
     * create automation run history task success
     * @param robotId robot id (required)
     * @param body  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> create automation run history task success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoCreateAutomationRunHistoryAsync(String robotId, Object body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = daoCreateAutomationRunHistoryValidateBeforeCall(robotId, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for daoGetAutomationRunContext
     * @param taskId task id (required)
     * @param actionId action id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history task context </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetAutomationRunContextCall(String taskId, String actionId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/databus/dao/automations/histories/{task_id}/contexts/{action_id}"
            .replace("{" + "task_id" + "}", localVarApiClient.escapeString(taskId.toString()))
            .replace("{" + "action_id" + "}", localVarApiClient.escapeString(actionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call daoGetAutomationRunContextValidateBeforeCall(String taskId, String actionId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException("Missing the required parameter 'taskId' when calling daoGetAutomationRunContext(Async)");
        }

        // verify the required parameter 'actionId' is set
        if (actionId == null) {
            throw new ApiException("Missing the required parameter 'actionId' when calling daoGetAutomationRunContext(Async)");
        }

        return daoGetAutomationRunContextCall(taskId, actionId, _callback);

    }

    /**
     * Get automation task input and output
     * Get automation task input and output
     * @param taskId task id (required)
     * @param actionId action id (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history task context </td><td>  -  </td></tr>
     </table>
     */
    public void daoGetAutomationRunContext(String taskId, String actionId) throws ApiException {
        daoGetAutomationRunContextWithHttpInfo(taskId, actionId);
    }

    /**
     * Get automation task input and output
     * Get automation task input and output
     * @param taskId task id (required)
     * @param actionId action id (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history task context </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> daoGetAutomationRunContextWithHttpInfo(String taskId, String actionId) throws ApiException {
        okhttp3.Call localVarCall = daoGetAutomationRunContextValidateBeforeCall(taskId, actionId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Get automation task input and output (asynchronously)
     * Get automation task input and output
     * @param taskId task id (required)
     * @param actionId action id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history task context </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetAutomationRunContextAsync(String taskId, String actionId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = daoGetAutomationRunContextValidateBeforeCall(taskId, actionId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for daoGetAutomationRunHistory
     * @param robotId robot id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history list </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetAutomationRunHistoryCall(String robotId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/databus/dao/automations/{robot_id}/histories"
            .replace("{" + "robot_id" + "}", localVarApiClient.escapeString(robotId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call daoGetAutomationRunHistoryValidateBeforeCall(String robotId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'robotId' is set
        if (robotId == null) {
            throw new ApiException("Missing the required parameter 'robotId' when calling daoGetAutomationRunHistory(Async)");
        }

        return daoGetAutomationRunHistoryCall(robotId, _callback);

    }

    /**
     * Get automation run history list
     * Get automation run history list
     * @param robotId robot id (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history list </td><td>  -  </td></tr>
     </table>
     */
    public void daoGetAutomationRunHistory(String robotId) throws ApiException {
        daoGetAutomationRunHistoryWithHttpInfo(robotId);
    }

    /**
     * Get automation run history list
     * Get automation run history list
     * @param robotId robot id (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history list </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> daoGetAutomationRunHistoryWithHttpInfo(String robotId) throws ApiException {
        okhttp3.Call localVarCall = daoGetAutomationRunHistoryValidateBeforeCall(robotId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Get automation run history list (asynchronously)
     * Get automation run history list
     * @param robotId robot id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history list </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetAutomationRunHistoryAsync(String robotId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = daoGetAutomationRunHistoryValidateBeforeCall(robotId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for daoGetAutomationRunHistoryDetail
     * @param taskId task id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history detail </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetAutomationRunHistoryDetailCall(String taskId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/databus/dao/automations/histories/{task_id}"
            .replace("{" + "task_id" + "}", localVarApiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call daoGetAutomationRunHistoryDetailValidateBeforeCall(String taskId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException("Missing the required parameter 'taskId' when calling daoGetAutomationRunHistoryDetail(Async)");
        }

        return daoGetAutomationRunHistoryDetailCall(taskId, _callback);

    }

    /**
     * Get automation run task details
     * Get automation run task details
     * @param taskId task id (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history detail </td><td>  -  </td></tr>
     </table>
     */
    public void daoGetAutomationRunHistoryDetail(String taskId) throws ApiException {
        daoGetAutomationRunHistoryDetailWithHttpInfo(taskId);
    }

    /**
     * Get automation run task details
     * Get automation run task details
     * @param taskId task id (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history detail </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> daoGetAutomationRunHistoryDetailWithHttpInfo(String taskId) throws ApiException {
        okhttp3.Call localVarCall = daoGetAutomationRunHistoryDetailValidateBeforeCall(taskId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Get automation run task details (asynchronously)
     * Get automation run task details
     * @param taskId task id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history detail </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetAutomationRunHistoryDetailAsync(String taskId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = daoGetAutomationRunHistoryDetailValidateBeforeCall(taskId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for daoGetRobotByRobotId
     * @param robotId Automation robot id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automation detail </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetRobotByRobotIdCall(String robotId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/databus/dao/automations/robots/{robot_id}"
            .replace("{" + "robot_id" + "}", localVarApiClient.escapeString(robotId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call daoGetRobotByRobotIdValidateBeforeCall(String robotId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'robotId' is set
        if (robotId == null) {
            throw new ApiException("Missing the required parameter 'robotId' when calling daoGetRobotByRobotId(Async)");
        }

        return daoGetRobotByRobotIdCall(robotId, _callback);

    }

    /**
     * Get automation robot detail.
     * Get automation robot detail.
     * @param robotId Automation robot id (required)
     * @return ApiResponseAutomationSO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automation detail </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponseAutomationSO daoGetRobotByRobotId(String robotId) throws ApiException {
        ApiResponse<ApiResponseAutomationSO> localVarResp = daoGetRobotByRobotIdWithHttpInfo(robotId);
        return localVarResp.getData();
    }

    /**
     * Get automation robot detail.
     * Get automation robot detail.
     * @param robotId Automation robot id (required)
     * @return ApiResponse&lt;ApiResponseAutomationSO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automation detail </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ApiResponseAutomationSO> daoGetRobotByRobotIdWithHttpInfo(String robotId) throws ApiException {
        okhttp3.Call localVarCall = daoGetRobotByRobotIdValidateBeforeCall(robotId, null);
        Type localVarReturnType = new TypeToken<ApiResponseAutomationSO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get automation robot detail. (asynchronously)
     * Get automation robot detail.
     * @param robotId Automation robot id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automation detail </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetRobotByRobotIdAsync(String robotId, final ApiCallback<ApiResponseAutomationSO> _callback) throws ApiException {

        okhttp3.Call localVarCall = daoGetRobotByRobotIdValidateBeforeCall(robotId, _callback);
        Type localVarReturnType = new TypeToken<ApiResponseAutomationSO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for daoGetRobotsByResourceId
     * @param resourceId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automations triggers </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetRobotsByResourceIdCall(String resourceId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/databus/dao/automations/robots";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (resourceId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("resource_id", resourceId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call daoGetRobotsByResourceIdValidateBeforeCall(String resourceId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'resourceId' is set
        if (resourceId == null) {
            throw new ApiException("Missing the required parameter 'resourceId' when calling daoGetRobotsByResourceId(Async)");
        }

        return daoGetRobotsByResourceIdCall(resourceId, _callback);

    }

    /**
     * get automations triggers
     * get automations triggers
     * @param resourceId  (required)
     * @return ApiResponseAutomationRobotIntroductionSO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automations triggers </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponseAutomationRobotIntroductionSO daoGetRobotsByResourceId(String resourceId) throws ApiException {
        ApiResponse<ApiResponseAutomationRobotIntroductionSO> localVarResp = daoGetRobotsByResourceIdWithHttpInfo(resourceId);
        return localVarResp.getData();
    }

    /**
     * get automations triggers
     * get automations triggers
     * @param resourceId  (required)
     * @return ApiResponse&lt;ApiResponseAutomationRobotIntroductionSO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automations triggers </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ApiResponseAutomationRobotIntroductionSO> daoGetRobotsByResourceIdWithHttpInfo(String resourceId) throws ApiException {
        okhttp3.Call localVarCall = daoGetRobotsByResourceIdValidateBeforeCall(resourceId, null);
        Type localVarReturnType = new TypeToken<ApiResponseAutomationRobotIntroductionSO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * get automations triggers (asynchronously)
     * get automations triggers
     * @param resourceId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automations triggers </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetRobotsByResourceIdAsync(String resourceId, final ApiCallback<ApiResponseAutomationRobotIntroductionSO> _callback) throws ApiException {

        okhttp3.Call localVarCall = daoGetRobotsByResourceIdValidateBeforeCall(resourceId, _callback);
        Type localVarReturnType = new TypeToken<ApiResponseAutomationRobotIntroductionSO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for daoGetRobotsTriggers
     * @param robotIds  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automations triggers </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetRobotsTriggersCall(List<String> robotIds, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/databus/dao/automations/triggers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (robotIds != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "robot_ids", robotIds));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call daoGetRobotsTriggersValidateBeforeCall(List<String> robotIds, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'robotIds' is set
        if (robotIds == null) {
            throw new ApiException("Missing the required parameter 'robotIds' when calling daoGetRobotsTriggers(Async)");
        }

        return daoGetRobotsTriggersCall(robotIds, _callback);

    }

    /**
     * get automations triggers
     * get automations triggers
     * @param robotIds  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automations triggers </td><td>  -  </td></tr>
     </table>
     */
    public void daoGetRobotsTriggers(List<String> robotIds) throws ApiException {
        daoGetRobotsTriggersWithHttpInfo(robotIds);
    }

    /**
     * get automations triggers
     * get automations triggers
     * @param robotIds  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automations triggers </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> daoGetRobotsTriggersWithHttpInfo(List<String> robotIds) throws ApiException {
        okhttp3.Call localVarCall = daoGetRobotsTriggersValidateBeforeCall(robotIds, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * get automations triggers (asynchronously)
     * get automations triggers
     * @param robotIds  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> get automations triggers </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoGetRobotsTriggersAsync(List<String> robotIds, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = daoGetRobotsTriggersValidateBeforeCall(robotIds, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for daoUpdateAutomationRobot
     * @param robotId robot id (required)
     * @param automationRobotUpdateRO  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Update automation robot successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoUpdateAutomationRobotCall(String robotId, AutomationRobotUpdateRO automationRobotUpdateRO, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = automationRobotUpdateRO;

        // create path and map variables
        String localVarPath = "/databus/dao/automations/robots/{robot_id}"
            .replace("{" + "robot_id" + "}", localVarApiClient.escapeString(robotId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call daoUpdateAutomationRobotValidateBeforeCall(String robotId, AutomationRobotUpdateRO automationRobotUpdateRO, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'robotId' is set
        if (robotId == null) {
            throw new ApiException("Missing the required parameter 'robotId' when calling daoUpdateAutomationRobot(Async)");
        }

        // verify the required parameter 'automationRobotUpdateRO' is set
        if (automationRobotUpdateRO == null) {
            throw new ApiException("Missing the required parameter 'automationRobotUpdateRO' when calling daoUpdateAutomationRobot(Async)");
        }

        return daoUpdateAutomationRobotCall(robotId, automationRobotUpdateRO, _callback);

    }

    /**
     * Get automation task input and output
     * Get automation task input and output
     * @param robotId robot id (required)
     * @param automationRobotUpdateRO  (required)
     * @return ApiResponseEmptySO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Update automation robot successfully </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponseEmptySO daoUpdateAutomationRobot(String robotId, AutomationRobotUpdateRO automationRobotUpdateRO) throws ApiException {
        ApiResponse<ApiResponseEmptySO> localVarResp = daoUpdateAutomationRobotWithHttpInfo(robotId, automationRobotUpdateRO);
        return localVarResp.getData();
    }

    /**
     * Get automation task input and output
     * Get automation task input and output
     * @param robotId robot id (required)
     * @param automationRobotUpdateRO  (required)
     * @return ApiResponse&lt;ApiResponseEmptySO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Update automation robot successfully </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ApiResponseEmptySO> daoUpdateAutomationRobotWithHttpInfo(String robotId, AutomationRobotUpdateRO automationRobotUpdateRO) throws ApiException {
        okhttp3.Call localVarCall = daoUpdateAutomationRobotValidateBeforeCall(robotId, automationRobotUpdateRO, null);
        Type localVarReturnType = new TypeToken<ApiResponseEmptySO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get automation task input and output (asynchronously)
     * Get automation task input and output
     * @param robotId robot id (required)
     * @param automationRobotUpdateRO  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Update automation robot successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoUpdateAutomationRobotAsync(String robotId, AutomationRobotUpdateRO automationRobotUpdateRO, final ApiCallback<ApiResponseEmptySO> _callback) throws ApiException {

        okhttp3.Call localVarCall = daoUpdateAutomationRobotValidateBeforeCall(robotId, automationRobotUpdateRO, _callback);
        Type localVarReturnType = new TypeToken<ApiResponseEmptySO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for daoUpdateAutomationRunHistoryStatus
     * @param taskId task id (required)
     * @param automationHistoryStatusRO  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history task context </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoUpdateAutomationRunHistoryStatusCall(String taskId, AutomationHistoryStatusRO automationHistoryStatusRO, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = automationHistoryStatusRO;

        // create path and map variables
        String localVarPath = "/databus/dao/automations/histories/{task_id}/status"
            .replace("{" + "task_id" + "}", localVarApiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call daoUpdateAutomationRunHistoryStatusValidateBeforeCall(String taskId, AutomationHistoryStatusRO automationHistoryStatusRO, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException("Missing the required parameter 'taskId' when calling daoUpdateAutomationRunHistoryStatus(Async)");
        }

        // verify the required parameter 'automationHistoryStatusRO' is set
        if (automationHistoryStatusRO == null) {
            throw new ApiException("Missing the required parameter 'automationHistoryStatusRO' when calling daoUpdateAutomationRunHistoryStatus(Async)");
        }

        return daoUpdateAutomationRunHistoryStatusCall(taskId, automationHistoryStatusRO, _callback);

    }

    /**
     * Get automation task input and output
     * Get automation task input and output
     * @param taskId task id (required)
     * @param automationHistoryStatusRO  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history task context </td><td>  -  </td></tr>
     </table>
     */
    public void daoUpdateAutomationRunHistoryStatus(String taskId, AutomationHistoryStatusRO automationHistoryStatusRO) throws ApiException {
        daoUpdateAutomationRunHistoryStatusWithHttpInfo(taskId, automationHistoryStatusRO);
    }

    /**
     * Get automation task input and output
     * Get automation task input and output
     * @param taskId task id (required)
     * @param automationHistoryStatusRO  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history task context </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> daoUpdateAutomationRunHistoryStatusWithHttpInfo(String taskId, AutomationHistoryStatusRO automationHistoryStatusRO) throws ApiException {
        okhttp3.Call localVarCall = daoUpdateAutomationRunHistoryStatusValidateBeforeCall(taskId, automationHistoryStatusRO, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Get automation task input and output (asynchronously)
     * Get automation task input and output
     * @param taskId task id (required)
     * @param automationHistoryStatusRO  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get automation run history task context </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call daoUpdateAutomationRunHistoryStatusAsync(String taskId, AutomationHistoryStatusRO automationHistoryStatusRO, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = daoUpdateAutomationRunHistoryStatusValidateBeforeCall(taskId, automationHistoryStatusRO, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
