import { Column, Entity } from 'typeorm';
import { BaseEntity } from '../../shared/entities/base.entity';
import { ICommentMsg } from '@apitable/core';

/**
 * Workbench-Record Comment
 */
@Entity('vika_datasheet_record_comment')
export class RecordCommentEntity extends BaseEntity {
  @Column({
    name: 'dst_id',
    nullable: false,
    comment: 'datasheet ID',
    length: 50,
  })
    dstId: string;

  @Column({
    name: 'record_id',
    nullable: false,
    comment: 'record ID',
    length: 50,
  })
    recordId: string;

  @Column({
    name: 'comment_id',
    nullable: false,
    comment: 'comment ID generated by chengeset',
    length: 50,
  })
    commentId: string;

  @Column('json', {
    name: 'comment_msg',
    nullable: false,
    comment: 'comment on rich text content',
  })
    commentMsg: ICommentMsg;

  @Column({
    name: 'revision',
    nullable: true,
    comment: 'revision',
    unsigned: true,
    default: () => 0,
    type: 'bigint',
    width: 20,
  })
    revision: number | null;

  @Column({
    name: 'unit_id',
    nullable: false,
    comment: 'operating member unitID(related#vika_unit#id)',
    width: 20,
    type: 'bigint',
  })
    unitId: string;
}
