import { EventRealTypeEnums } from 'event_manager';
import { ResourceType } from '../../../types/resource_types';
import { IAtomEventType } from '../interface';
import { OPEventNameEnums } from './../../const';
import { AnyObject, IOPBaseContext } from './../../interface/event.interface';

interface IFormSubmitted {
  formId: string;
  datasheet: {
    id: string;
    name: string;
  };
  record: {
    id: string;
    url: string;
    fields: AnyObject;
  }
}

export class OPEventFormSubmitted extends IAtomEventType<IFormSubmitted> {
  eventName = OPEventNameEnums.FormSubmitted;
  realType = EventRealTypeEnums.REAL;
  scope = ResourceType.Form;

  // The event of the form form is not generated by the test op, but dispatches the event directly in the only entry function.
  test(opContext: IOPBaseContext) {
    return {
      pass: false,
      context: null
    };
  }
}