import { t, Strings } from '@apitable/core';

export default {
  // 块级元素
  paragraph: t(Strings.paragraph),
  headingOne: t(Strings.heading_one),
  headingTwo: t(Strings.heading_two),
  headingThree: t(Strings.heading_three),
  headingFour: t(Strings.heading_four),
  headingFive: t(Strings.heading_five),
  headingSix: t(Strings.heading_six),
  image: t(Strings.image),
  orderedList: t(Strings.ordered_list),
  unorderedList: t(Strings.unordered_list),
  taskList: t(Strings.task_list),
  quote: t(Strings.quote),
  codeBlockWrap: t(Strings.code_block),
  divider: t(Strings.divider),
  table: t(Strings.table),
  // 内联元素
  link: t(Strings.link),
  italic: t(Strings.italic),
  underLine: t(Strings.under_line),
  strikeThrough: t(Strings.strikethrough),
  bold: t(Strings.bold),
  inlineCode: t(Strings.inline_code),
  mention: t(Strings.mention),
  highlight: t(Strings.highlight),
  // 对齐方式
  alignLeft: t(Strings.align_left),
  alignCenter: t(Strings.align_center),
  alignRight: t(Strings.align_right),
  // 其他
  ok: t(Strings.submit),
  cancel: t(Strings.cancel),
  text: t(Strings.text),
  edit: t(Strings.edit),
  unlink: t(Strings.unlink),
  placeholder: t(Strings.editor_placeholder),
  commonFormat: t(Strings.common_format),
  insertBelow: t(Strings.insert_below),
  insertAbove: t(Strings.insert_above),
  mediaElement: t(Strings.media_element),
  associatedElement: t(Strings.associated_element),
  addImage: t(Strings.add_image),
  imageSizeError: t(Strings.image_limit, { number: 2 }),
  imageTypeError: t(Strings.support_image_formats),
  imageUploading: t(Strings.image_uploading),
  copySuccess: t(Strings.copy_success),
  copyFailed: t(Strings.copy_failed),
  delete: t(Strings.delete),
  visit: t(Strings.visit),
  linkInputPlaceholder: t(Strings.link_input_placeholder)
};