import { IJOTAction, IOperation } from 'engine/ot/interface';
import { ResourceType } from '../../types/resource_types';
import { EventAtomTypeEnums, EventRealTypeEnums, EventSourceTypeEnums, OPEventNameEnums } from '../const';

export type AnyObject = Record<string, any>;

export interface IEventBase {
  eventName: OPEventNameEnums;
  realType: EventRealTypeEnums;
  atomType: EventAtomTypeEnums;
  scope: ResourceType;
}

export interface IEventTestResult<T> {
  pass: boolean; // whether the event fires
  context: null | AnyObject & T; // custom context returned by the event
}

export interface IRealAtomEvent extends IEventBase {
  realType: EventRealTypeEnums.REAL;
  atomType: EventAtomTypeEnums.ATOM;
}

export interface IVirtualAtomEvent extends IEventBase {
  realType: EventRealTypeEnums.VIRTUAL;
  atomType: EventAtomTypeEnums.ATOM;
}

export interface IRealCombEvent extends IEventBase {
  realType: EventRealTypeEnums.REAL;
  atomType: EventAtomTypeEnums.COMB;
}

export interface IVirtualCombEvent extends IEventBase {
  realType: EventRealTypeEnums.VIRTUAL;
  atomType: EventAtomTypeEnums.COMB;
}

export type IAtomEvent = IRealAtomEvent | IVirtualAtomEvent;
export type ICombEvent = IRealCombEvent | IVirtualCombEvent;
export type IOPEvent = IAtomEvent | ICombEvent;

export type IEventInstance<T> = T & {
  context: AnyObject,
  sourceType: EventSourceTypeEnums;
};

// op context assembled by changeset
export interface IOPBaseContext {
  // ops generated by cmd
  op: IOperation;
  // single op action
  action: IJOTAction;
  // Resource Type
  resourceType: ResourceType;
  // resource id
  resourceId: string;
}
