/*
 * databus-server
 * databus-server APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apitable.databusclient.model;

import java.util.Objects;
import com.apitable.databusclient.model.AutomationActionIntroductionPO;
import com.apitable.databusclient.model.AutomationRobotPO;
import com.apitable.databusclient.model.AutomationTriggerIntroductionPO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.apitable.databusclient.JSON;

/**
 * AutomationRobotIntroductionSO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-06T19:03:51.398869+08:00[Asia/Shanghai]")
public class AutomationRobotIntroductionSO {
  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private List<AutomationActionIntroductionPO> actions = new ArrayList<>();

  public static final String SERIALIZED_NAME_ROBOTS = "robots";
  @SerializedName(SERIALIZED_NAME_ROBOTS)
  private List<AutomationRobotPO> robots = new ArrayList<>();

  public static final String SERIALIZED_NAME_TRIGGERS = "triggers";
  @SerializedName(SERIALIZED_NAME_TRIGGERS)
  private List<AutomationTriggerIntroductionPO> triggers = new ArrayList<>();

  public AutomationRobotIntroductionSO() {
  }

  public AutomationRobotIntroductionSO actions(List<AutomationActionIntroductionPO> actions) {
    
    this.actions = actions;
    return this;
  }

  public AutomationRobotIntroductionSO addActionsItem(AutomationActionIntroductionPO actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nonnull
  public List<AutomationActionIntroductionPO> getActions() {
    return actions;
  }


  public void setActions(List<AutomationActionIntroductionPO> actions) {
    this.actions = actions;
  }


  public AutomationRobotIntroductionSO robots(List<AutomationRobotPO> robots) {
    
    this.robots = robots;
    return this;
  }

  public AutomationRobotIntroductionSO addRobotsItem(AutomationRobotPO robotsItem) {
    if (this.robots == null) {
      this.robots = new ArrayList<>();
    }
    this.robots.add(robotsItem);
    return this;
  }

   /**
   * Get robots
   * @return robots
  **/
  @javax.annotation.Nonnull
  public List<AutomationRobotPO> getRobots() {
    return robots;
  }


  public void setRobots(List<AutomationRobotPO> robots) {
    this.robots = robots;
  }


  public AutomationRobotIntroductionSO triggers(List<AutomationTriggerIntroductionPO> triggers) {
    
    this.triggers = triggers;
    return this;
  }

  public AutomationRobotIntroductionSO addTriggersItem(AutomationTriggerIntroductionPO triggersItem) {
    if (this.triggers == null) {
      this.triggers = new ArrayList<>();
    }
    this.triggers.add(triggersItem);
    return this;
  }

   /**
   * Get triggers
   * @return triggers
  **/
  @javax.annotation.Nonnull
  public List<AutomationTriggerIntroductionPO> getTriggers() {
    return triggers;
  }


  public void setTriggers(List<AutomationTriggerIntroductionPO> triggers) {
    this.triggers = triggers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutomationRobotIntroductionSO automationRobotIntroductionSO = (AutomationRobotIntroductionSO) o;
    return Objects.equals(this.actions, automationRobotIntroductionSO.actions) &&
        Objects.equals(this.robots, automationRobotIntroductionSO.robots) &&
        Objects.equals(this.triggers, automationRobotIntroductionSO.triggers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actions, robots, triggers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutomationRobotIntroductionSO {\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    robots: ").append(toIndentedString(robots)).append("\n");
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("actions");
    openapiFields.add("robots");
    openapiFields.add("triggers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("actions");
    openapiRequiredFields.add("robots");
    openapiRequiredFields.add("triggers");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AutomationRobotIntroductionSO
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AutomationRobotIntroductionSO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AutomationRobotIntroductionSO is not found in the empty JSON string", AutomationRobotIntroductionSO.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AutomationRobotIntroductionSO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AutomationRobotIntroductionSO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AutomationRobotIntroductionSO.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("actions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `actions` to be an array in the JSON string but got `%s`", jsonObj.get("actions").toString()));
      }

      JsonArray jsonArrayactions = jsonObj.getAsJsonArray("actions");
      // validate the required field `actions` (array)
      for (int i = 0; i < jsonArrayactions.size(); i++) {
        AutomationActionIntroductionPO.validateJsonElement(jsonArrayactions.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("robots").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `robots` to be an array in the JSON string but got `%s`", jsonObj.get("robots").toString()));
      }

      JsonArray jsonArrayrobots = jsonObj.getAsJsonArray("robots");
      // validate the required field `robots` (array)
      for (int i = 0; i < jsonArrayrobots.size(); i++) {
        AutomationRobotPO.validateJsonElement(jsonArrayrobots.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("triggers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `triggers` to be an array in the JSON string but got `%s`", jsonObj.get("triggers").toString()));
      }

      JsonArray jsonArraytriggers = jsonObj.getAsJsonArray("triggers");
      // validate the required field `triggers` (array)
      for (int i = 0; i < jsonArraytriggers.size(); i++) {
        AutomationTriggerIntroductionPO.validateJsonElement(jsonArraytriggers.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AutomationRobotIntroductionSO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AutomationRobotIntroductionSO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AutomationRobotIntroductionSO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AutomationRobotIntroductionSO.class));

       return (TypeAdapter<T>) new TypeAdapter<AutomationRobotIntroductionSO>() {
           @Override
           public void write(JsonWriter out, AutomationRobotIntroductionSO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AutomationRobotIntroductionSO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AutomationRobotIntroductionSO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AutomationRobotIntroductionSO
  * @throws IOException if the JSON string is invalid with respect to AutomationRobotIntroductionSO
  */
  public static AutomationRobotIntroductionSO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AutomationRobotIntroductionSO.class);
  }

 /**
  * Convert an instance of AutomationRobotIntroductionSO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

