/*
 * databus-server
 * databus-server APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apitable.databusclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets DateFormat
 */
@JsonAdapter(DateFormat.Adapter.class)
public enum DateFormat {
  
  SYYYYMMDD("SYyyyMmDd"),
  
  UYYYYMMDD("UYyyyMmDd"),
  
  DDMMYYYY("DdMmYyyy"),
  
  YYYYMM("YyyyMm"),
  
  MMDD("MmDd"),
  
  YYYY("YYYY"),
  
  MM("MM"),
  
  DD("DD");

  private String value;

  DateFormat(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DateFormat fromValue(String value) {
    for (DateFormat b : DateFormat.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DateFormat> {
    @Override
    public void write(final JsonWriter jsonWriter, final DateFormat enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DateFormat read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DateFormat.fromValue(value);
    }
  }
}

