import { IPermissions } from 'core';

export function createMockPermissions(): IPermissions {
  return {
    allowEditConfigurable: true,
    allowSaveConfigurable: true,
    childCreatable: true,
    copyable: true,
    descriptionEditable: true,
    editable: true,
    exportable: true,
    iconEditable: true,
    importable: true,
    manageable: true,
    movable: true,
    nodeAssignable: true,
    readable: true,
    removable: true,
    renamable: true,
    sharable: true,
    templateCreatable: true,
    viewCreatable: true,
    viewRenamable: true,
    viewRemovable: true,
    viewMovable: true,
    viewExportable: true,
    viewFilterable: true,
    columnSortable: true,
    columnHideable: true,
    fieldSortable: true,
    fieldGroupable: true,
    rowHighEditable: true,
    columnWidthEditable: true,
    columnCountEditable: true,
    rowSortable: true,
    fieldCreatable: true,
    fieldRenamable: true,
    fieldPropertyEditable: true,
    fieldRemovable: true,
    rowCreatable: true,
    rowRemovable: true,
    rowArchivable: true,
    rowUnarchivable: true,
    cellEditable: true,
    fieldPermissionManageable: true,
    viewLayoutEditable: true,
    viewStyleEditable: true,
    viewKeyFieldEditable: true,
    viewColorOptionEditable: true,
    viewManualSaveManageable: true,
    viewOptionSaveEditable: true
  };
}
