[package]
edition = "2021"
name = "room-api"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.69"
chrono = "0.4.23"
futures = "0.3.26"
maplit = "1.0.2"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.10.14", default-features = false, features = [
  "napi8",
  "tokio_rt",
  "anyhow",
  "chrono_date",
  "serde-json",
] }
napi-derive = "2.10.1"
once_cell = "1.17.1"
percent-encoding = "2.2.0"
sea-orm = { git = "https://github.com/arucil/sea-orm", features = [
  "sqlx-mysql",
  "runtime-tokio-rustls",
  "macros",
  "mock",
] }
seahash = "4.1.0"
serde = "1.0.152"
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = [
  "parking_lot",
  "rt-multi-thread",
  "macros",
] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
opt-level = 3

[dev-dependencies]
pretty_assertions = "1.3.0"
serial_test = "1.0.0"
tokio-test = "0.4.2"
