[package]
edition = "2021"
name = "room-api"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1.0.69", features = ["backtrace"]}
async-trait = "0.1.64"
fred = { version = "6.0.0", features = ["enable-rustls"] }
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
futures = "0.3.26"
http = "0.2.9"
http-serde = "1.1.2"
mysql_async = { version = "0.31.3", default-features = false, features = ["default-rustls"] }
mysql_common = "0.29.2"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.0", default-features = false, features = [
  "napi8",
  "tokio_rt",
  "anyhow",
  "serde-json",
] }
napi-derive = "2.12.1"
once_cell = "1.17.1"
regex = "1.7.1"
seahash = "4.1.0"
seq-macro = "0.3.3"
serde = { version = "1.0.152", features = ["rc"] }
serde_json = "1.0.93"
serde_qs = "0.12.0"
serde_repr = "0.1.11"
shaku = "0.6.1"
surf = { version = "2.3.2", features = [
  "encoding",
  "h1-client-rustls",
], default-features = false }
thiserror = "1.0.39"
time = { version = "0.3.20" }
tokio = { version = "1.25.0", features = [
  "parking_lot",
  "rt-multi-thread",
  "macros",
] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
url-escape = "0.1.1"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
opt-level = 3

[dev-dependencies]
fred = { version = "6.0.0", features = ["enable-rustls", "mocks"] }
pretty_assertions = "1.3.0"
tokio-test = "0.4.2"
rstest = "0.16.0"
rstest_reuse = "0.5.0"
