/*
 * databus-server
 * databus-server APIs
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apitable.starter.databus.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.apitable.starter.databus.client.model.BaseDatasheetPackSO;
import com.apitable.starter.databus.client.model.DatasheetSnapshotSO;
import com.apitable.starter.databus.client.model.NodeSO;
import com.apitable.starter.databus.client.model.UnitSO;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DatasheetPackSO
 */
@JsonPropertyOrder({
  DatasheetPackSO.JSON_PROPERTY_DATASHEET,
  DatasheetPackSO.JSON_PROPERTY_FIELD_PERMISSION_MAP,
  DatasheetPackSO.JSON_PROPERTY_FOREIGN_DATASHEET_MAP,
  DatasheetPackSO.JSON_PROPERTY_SNAPSHOT,
  DatasheetPackSO.JSON_PROPERTY_UNITS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DatasheetPackSO {
  public static final String JSON_PROPERTY_DATASHEET = "datasheet";
  private NodeSO datasheet;

  public static final String JSON_PROPERTY_FIELD_PERMISSION_MAP = "fieldPermissionMap";
  private Object fieldPermissionMap = null;

  public static final String JSON_PROPERTY_FOREIGN_DATASHEET_MAP = "foreignDatasheetMap";
  private Map<String, BaseDatasheetPackSO> foreignDatasheetMap;

  public static final String JSON_PROPERTY_SNAPSHOT = "snapshot";
  private DatasheetSnapshotSO snapshot;

  public static final String JSON_PROPERTY_UNITS = "units";
  private List<UnitSO> units;

  public DatasheetPackSO() {
  }

  public DatasheetPackSO datasheet(NodeSO datasheet) {
    
    this.datasheet = datasheet;
    return this;
  }

   /**
   * Get datasheet
   * @return datasheet
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATASHEET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public NodeSO getDatasheet() {
    return datasheet;
  }


  @JsonProperty(JSON_PROPERTY_DATASHEET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDatasheet(NodeSO datasheet) {
    this.datasheet = datasheet;
  }


  public DatasheetPackSO fieldPermissionMap(Object fieldPermissionMap) {
    
    this.fieldPermissionMap = fieldPermissionMap;
    return this;
  }

   /**
   * Get fieldPermissionMap
   * @return fieldPermissionMap
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELD_PERMISSION_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getFieldPermissionMap() {
    return fieldPermissionMap;
  }


  @JsonProperty(JSON_PROPERTY_FIELD_PERMISSION_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFieldPermissionMap(Object fieldPermissionMap) {
    this.fieldPermissionMap = fieldPermissionMap;
  }


  public DatasheetPackSO foreignDatasheetMap(Map<String, BaseDatasheetPackSO> foreignDatasheetMap) {
    
    this.foreignDatasheetMap = foreignDatasheetMap;
    return this;
  }

  public DatasheetPackSO putForeignDatasheetMapItem(String key, BaseDatasheetPackSO foreignDatasheetMapItem) {
    if (this.foreignDatasheetMap == null) {
      this.foreignDatasheetMap = new HashMap<>();
    }
    this.foreignDatasheetMap.put(key, foreignDatasheetMapItem);
    return this;
  }

   /**
   * Get foreignDatasheetMap
   * @return foreignDatasheetMap
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOREIGN_DATASHEET_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, BaseDatasheetPackSO> getForeignDatasheetMap() {
    return foreignDatasheetMap;
  }


  @JsonProperty(JSON_PROPERTY_FOREIGN_DATASHEET_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForeignDatasheetMap(Map<String, BaseDatasheetPackSO> foreignDatasheetMap) {
    this.foreignDatasheetMap = foreignDatasheetMap;
  }


  public DatasheetPackSO snapshot(DatasheetSnapshotSO snapshot) {
    
    this.snapshot = snapshot;
    return this;
  }

   /**
   * Get snapshot
   * @return snapshot
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DatasheetSnapshotSO getSnapshot() {
    return snapshot;
  }


  @JsonProperty(JSON_PROPERTY_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSnapshot(DatasheetSnapshotSO snapshot) {
    this.snapshot = snapshot;
  }


  public DatasheetPackSO units(List<UnitSO> units) {
    
    this.units = units;
    return this;
  }

  public DatasheetPackSO addUnitsItem(UnitSO unitsItem) {
    if (this.units == null) {
      this.units = new ArrayList<>();
    }
    this.units.add(unitsItem);
    return this;
  }

   /**
   * Get units
   * @return units
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UnitSO> getUnits() {
    return units;
  }


  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnits(List<UnitSO> units) {
    this.units = units;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasheetPackSO datasheetPackSO = (DatasheetPackSO) o;
    return Objects.equals(this.datasheet, datasheetPackSO.datasheet) &&
        Objects.equals(this.fieldPermissionMap, datasheetPackSO.fieldPermissionMap) &&
        Objects.equals(this.foreignDatasheetMap, datasheetPackSO.foreignDatasheetMap) &&
        Objects.equals(this.snapshot, datasheetPackSO.snapshot) &&
        Objects.equals(this.units, datasheetPackSO.units);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasheet, fieldPermissionMap, foreignDatasheetMap, snapshot, units);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasheetPackSO {\n");
    sb.append("    datasheet: ").append(toIndentedString(datasheet)).append("\n");
    sb.append("    fieldPermissionMap: ").append(toIndentedString(fieldPermissionMap)).append("\n");
    sb.append("    foreignDatasheetMap: ").append(toIndentedString(foreignDatasheetMap)).append("\n");
    sb.append("    snapshot: ").append(toIndentedString(snapshot)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

