/*
 * databus-server
 * databus-server APIs
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apitable.starter.databus.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.apitable.starter.databus.client.model.FieldKindSO;
import com.apitable.starter.databus.client.model.FieldPropertySO;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FieldSO
 */
@JsonPropertyOrder({
  FieldSO.JSON_PROPERTY_DESC,
  FieldSO.JSON_PROPERTY_ID,
  FieldSO.JSON_PROPERTY_NAME,
  FieldSO.JSON_PROPERTY_PROPERTY,
  FieldSO.JSON_PROPERTY_REQUIRED,
  FieldSO.JSON_PROPERTY_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FieldSO {
  public static final String JSON_PROPERTY_DESC = "desc";
  private JsonNullable<String> desc = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PROPERTY = "property";
  private JsonNullable<FieldPropertySO> property = JsonNullable.<FieldPropertySO>undefined();

  public static final String JSON_PROPERTY_REQUIRED = "required";
  private JsonNullable<Boolean> required = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_TYPE = "type";
  private FieldKindSO type;

  public FieldSO() {
  }

  public FieldSO desc(String desc) {
    this.desc = JsonNullable.<String>of(desc);
    
    return this;
  }

   /**
   * Get desc
   * @return desc
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public String getDesc() {
        return desc.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDesc_JsonNullable() {
    return desc;
  }
  
  @JsonProperty(JSON_PROPERTY_DESC)
  public void setDesc_JsonNullable(JsonNullable<String> desc) {
    this.desc = desc;
  }

  public void setDesc(String desc) {
    this.desc = JsonNullable.<String>of(desc);
  }


  public FieldSO id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public FieldSO name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public FieldSO property(FieldPropertySO property) {
    this.property = JsonNullable.<FieldPropertySO>of(property);
    
    return this;
  }

   /**
   * Get property
   * @return property
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public FieldPropertySO getProperty() {
        return property.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<FieldPropertySO> getProperty_JsonNullable() {
    return property;
  }
  
  @JsonProperty(JSON_PROPERTY_PROPERTY)
  public void setProperty_JsonNullable(JsonNullable<FieldPropertySO> property) {
    this.property = property;
  }

  public void setProperty(FieldPropertySO property) {
    this.property = JsonNullable.<FieldPropertySO>of(property);
  }


  public FieldSO required(Boolean required) {
    this.required = JsonNullable.<Boolean>of(required);
    
    return this;
  }

   /**
   * Get required
   * @return required
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public Boolean getRequired() {
        return required.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getRequired_JsonNullable() {
    return required;
  }
  
  @JsonProperty(JSON_PROPERTY_REQUIRED)
  public void setRequired_JsonNullable(JsonNullable<Boolean> required) {
    this.required = required;
  }

  public void setRequired(Boolean required) {
    this.required = JsonNullable.<Boolean>of(required);
  }


  public FieldSO type(FieldKindSO type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FieldKindSO getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(FieldKindSO type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldSO fieldSO = (FieldSO) o;
    return equalsNullable(this.desc, fieldSO.desc) &&
        Objects.equals(this.id, fieldSO.id) &&
        Objects.equals(this.name, fieldSO.name) &&
        equalsNullable(this.property, fieldSO.property) &&
        equalsNullable(this.required, fieldSO.required) &&
        Objects.equals(this.type, fieldSO.type);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(desc), id, name, hashCodeNullable(property), hashCodeNullable(required), type);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldSO {\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

