/*
 * databus-server
 * databus-server APIs
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apitable.starter.databus.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.apitable.starter.databus.client.model.FilterConjunction;
import com.apitable.starter.databus.client.model.IFilterCondition;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * IFilterInfo
 */
@JsonPropertyOrder({
  IFilterInfo.JSON_PROPERTY_CONDITIONS,
  IFilterInfo.JSON_PROPERTY_CONJUNCTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IFilterInfo {
  public static final String JSON_PROPERTY_CONDITIONS = "conditions";
  private List<IFilterCondition> conditions;

  public static final String JSON_PROPERTY_CONJUNCTION = "conjunction";
  private FilterConjunction conjunction;

  public IFilterInfo() {
  }

  public IFilterInfo conditions(List<IFilterCondition> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public IFilterInfo addConditionsItem(IFilterCondition conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<IFilterCondition> getConditions() {
    return conditions;
  }


  @JsonProperty(JSON_PROPERTY_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConditions(List<IFilterCondition> conditions) {
    this.conditions = conditions;
  }


  public IFilterInfo conjunction(FilterConjunction conjunction) {
    
    this.conjunction = conjunction;
    return this;
  }

   /**
   * Get conjunction
   * @return conjunction
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONJUNCTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FilterConjunction getConjunction() {
    return conjunction;
  }


  @JsonProperty(JSON_PROPERTY_CONJUNCTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConjunction(FilterConjunction conjunction) {
    this.conjunction = conjunction;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IFilterInfo ifilterInfo = (IFilterInfo) o;
    return Objects.equals(this.conditions, ifilterInfo.conditions) &&
        Objects.equals(this.conjunction, ifilterInfo.conjunction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, conjunction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IFilterInfo {\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    conjunction: ").append(toIndentedString(conjunction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

