/*
 * databus-server
 * databus-server APIs
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.apitable.starter.databus.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.apitable.starter.databus.client.model.IFilterInfo;
import com.apitable.starter.databus.client.model.ISortInfo;
import com.apitable.starter.databus.client.model.ISortedField;
import com.apitable.starter.databus.client.model.IViewLockInfo;
import com.apitable.starter.databus.client.model.ViewColumnSO;
import com.apitable.starter.databus.client.model.ViewRowSO;
import com.apitable.starter.databus.client.model.ViewStyleSo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ViewSO
 */
@JsonPropertyOrder({
  ViewSO.JSON_PROPERTY_AUTO_HEAD_HEIGHT,
  ViewSO.JSON_PROPERTY_AUTO_SAVE,
  ViewSO.JSON_PROPERTY_COLUMNS,
  ViewSO.JSON_PROPERTY_DESCRIPTION,
  ViewSO.JSON_PROPERTY_DISPLAY_HIDDEN_COLUMN_WITHIN_MIRROR,
  ViewSO.JSON_PROPERTY_FILTER_INFO,
  ViewSO.JSON_PROPERTY_FROZEN_COLUMN_COUNT,
  ViewSO.JSON_PROPERTY_GROUP_INFO,
  ViewSO.JSON_PROPERTY_HIDDEN,
  ViewSO.JSON_PROPERTY_ID,
  ViewSO.JSON_PROPERTY_LOCK_INFO,
  ViewSO.JSON_PROPERTY_NAME,
  ViewSO.JSON_PROPERTY_ROW_HEIGHT_LEVEL,
  ViewSO.JSON_PROPERTY_ROWS,
  ViewSO.JSON_PROPERTY_SORT_INFO,
  ViewSO.JSON_PROPERTY_STYLE,
  ViewSO.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ViewSO {
  public static final String JSON_PROPERTY_AUTO_HEAD_HEIGHT = "autoHeadHeight";
  private Boolean autoHeadHeight;

  public static final String JSON_PROPERTY_AUTO_SAVE = "autoSave";
  private Boolean autoSave;

  public static final String JSON_PROPERTY_COLUMNS = "columns";
  private List<ViewColumnSO> columns = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_DISPLAY_HIDDEN_COLUMN_WITHIN_MIRROR = "displayHiddenColumnWithinMirror";
  private Boolean displayHiddenColumnWithinMirror;

  public static final String JSON_PROPERTY_FILTER_INFO = "filterInfo";
  private IFilterInfo filterInfo;

  public static final String JSON_PROPERTY_FROZEN_COLUMN_COUNT = "frozenColumnCount";
  private Integer frozenColumnCount;

  public static final String JSON_PROPERTY_GROUP_INFO = "groupInfo";
  private List<ISortedField> groupInfo;

  public static final String JSON_PROPERTY_HIDDEN = "hidden";
  private Boolean hidden;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_LOCK_INFO = "lockInfo";
  private IViewLockInfo lockInfo;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ROW_HEIGHT_LEVEL = "rowHeightLevel";
  private Integer rowHeightLevel;

  public static final String JSON_PROPERTY_ROWS = "rows";
  private List<ViewRowSO> rows;

  public static final String JSON_PROPERTY_SORT_INFO = "sortInfo";
  private ISortInfo sortInfo;

  public static final String JSON_PROPERTY_STYLE = "style";
  private ViewStyleSo style;

  public static final String JSON_PROPERTY_TYPE = "type";
  private Long type;

  public ViewSO() {
  }

  public ViewSO autoHeadHeight(Boolean autoHeadHeight) {
    
    this.autoHeadHeight = autoHeadHeight;
    return this;
  }

   /**
   * Get autoHeadHeight
   * @return autoHeadHeight
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTO_HEAD_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutoHeadHeight() {
    return autoHeadHeight;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_HEAD_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoHeadHeight(Boolean autoHeadHeight) {
    this.autoHeadHeight = autoHeadHeight;
  }


  public ViewSO autoSave(Boolean autoSave) {
    
    this.autoSave = autoSave;
    return this;
  }

   /**
   * Get autoSave
   * @return autoSave
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTO_SAVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutoSave() {
    return autoSave;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_SAVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoSave(Boolean autoSave) {
    this.autoSave = autoSave;
  }


  public ViewSO columns(List<ViewColumnSO> columns) {
    
    this.columns = columns;
    return this;
  }

  public ViewSO addColumnsItem(ViewColumnSO columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

   /**
   * Get columns
   * @return columns
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ViewColumnSO> getColumns() {
    return columns;
  }


  @JsonProperty(JSON_PROPERTY_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColumns(List<ViewColumnSO> columns) {
    this.columns = columns;
  }


  public ViewSO description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ViewSO displayHiddenColumnWithinMirror(Boolean displayHiddenColumnWithinMirror) {
    
    this.displayHiddenColumnWithinMirror = displayHiddenColumnWithinMirror;
    return this;
  }

   /**
   * Get displayHiddenColumnWithinMirror
   * @return displayHiddenColumnWithinMirror
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_HIDDEN_COLUMN_WITHIN_MIRROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisplayHiddenColumnWithinMirror() {
    return displayHiddenColumnWithinMirror;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_HIDDEN_COLUMN_WITHIN_MIRROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayHiddenColumnWithinMirror(Boolean displayHiddenColumnWithinMirror) {
    this.displayHiddenColumnWithinMirror = displayHiddenColumnWithinMirror;
  }


  public ViewSO filterInfo(IFilterInfo filterInfo) {
    
    this.filterInfo = filterInfo;
    return this;
  }

   /**
   * Get filterInfo
   * @return filterInfo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IFilterInfo getFilterInfo() {
    return filterInfo;
  }


  @JsonProperty(JSON_PROPERTY_FILTER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilterInfo(IFilterInfo filterInfo) {
    this.filterInfo = filterInfo;
  }


  public ViewSO frozenColumnCount(Integer frozenColumnCount) {
    
    this.frozenColumnCount = frozenColumnCount;
    return this;
  }

   /**
   * Get frozenColumnCount
   * @return frozenColumnCount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROZEN_COLUMN_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFrozenColumnCount() {
    return frozenColumnCount;
  }


  @JsonProperty(JSON_PROPERTY_FROZEN_COLUMN_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrozenColumnCount(Integer frozenColumnCount) {
    this.frozenColumnCount = frozenColumnCount;
  }


  public ViewSO groupInfo(List<ISortedField> groupInfo) {
    
    this.groupInfo = groupInfo;
    return this;
  }

  public ViewSO addGroupInfoItem(ISortedField groupInfoItem) {
    if (this.groupInfo == null) {
      this.groupInfo = new ArrayList<>();
    }
    this.groupInfo.add(groupInfoItem);
    return this;
  }

   /**
   * Get groupInfo
   * @return groupInfo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ISortedField> getGroupInfo() {
    return groupInfo;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupInfo(List<ISortedField> groupInfo) {
    this.groupInfo = groupInfo;
  }


  public ViewSO hidden(Boolean hidden) {
    
    this.hidden = hidden;
    return this;
  }

   /**
   * Get hidden
   * @return hidden
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHidden() {
    return hidden;
  }


  @JsonProperty(JSON_PROPERTY_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }


  public ViewSO id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ViewSO lockInfo(IViewLockInfo lockInfo) {
    
    this.lockInfo = lockInfo;
    return this;
  }

   /**
   * Get lockInfo
   * @return lockInfo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCK_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IViewLockInfo getLockInfo() {
    return lockInfo;
  }


  @JsonProperty(JSON_PROPERTY_LOCK_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockInfo(IViewLockInfo lockInfo) {
    this.lockInfo = lockInfo;
  }


  public ViewSO name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ViewSO rowHeightLevel(Integer rowHeightLevel) {
    
    this.rowHeightLevel = rowHeightLevel;
    return this;
  }

   /**
   * Get rowHeightLevel
   * @return rowHeightLevel
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROW_HEIGHT_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRowHeightLevel() {
    return rowHeightLevel;
  }


  @JsonProperty(JSON_PROPERTY_ROW_HEIGHT_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRowHeightLevel(Integer rowHeightLevel) {
    this.rowHeightLevel = rowHeightLevel;
  }


  public ViewSO rows(List<ViewRowSO> rows) {
    
    this.rows = rows;
    return this;
  }

  public ViewSO addRowsItem(ViewRowSO rowsItem) {
    if (this.rows == null) {
      this.rows = new ArrayList<>();
    }
    this.rows.add(rowsItem);
    return this;
  }

   /**
   * Get rows
   * @return rows
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ViewRowSO> getRows() {
    return rows;
  }


  @JsonProperty(JSON_PROPERTY_ROWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRows(List<ViewRowSO> rows) {
    this.rows = rows;
  }


  public ViewSO sortInfo(ISortInfo sortInfo) {
    
    this.sortInfo = sortInfo;
    return this;
  }

   /**
   * Get sortInfo
   * @return sortInfo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SORT_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ISortInfo getSortInfo() {
    return sortInfo;
  }


  @JsonProperty(JSON_PROPERTY_SORT_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSortInfo(ISortInfo sortInfo) {
    this.sortInfo = sortInfo;
  }


  public ViewSO style(ViewStyleSo style) {
    
    this.style = style;
    return this;
  }

   /**
   * Get style
   * @return style
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ViewStyleSo getStyle() {
    return style;
  }


  @JsonProperty(JSON_PROPERTY_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStyle(ViewStyleSo style) {
    this.style = style;
  }


  public ViewSO type(Long type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * minimum: 0
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(Long type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ViewSO viewSO = (ViewSO) o;
    return Objects.equals(this.autoHeadHeight, viewSO.autoHeadHeight) &&
        Objects.equals(this.autoSave, viewSO.autoSave) &&
        Objects.equals(this.columns, viewSO.columns) &&
        Objects.equals(this.description, viewSO.description) &&
        Objects.equals(this.displayHiddenColumnWithinMirror, viewSO.displayHiddenColumnWithinMirror) &&
        Objects.equals(this.filterInfo, viewSO.filterInfo) &&
        Objects.equals(this.frozenColumnCount, viewSO.frozenColumnCount) &&
        Objects.equals(this.groupInfo, viewSO.groupInfo) &&
        Objects.equals(this.hidden, viewSO.hidden) &&
        Objects.equals(this.id, viewSO.id) &&
        Objects.equals(this.lockInfo, viewSO.lockInfo) &&
        Objects.equals(this.name, viewSO.name) &&
        Objects.equals(this.rowHeightLevel, viewSO.rowHeightLevel) &&
        Objects.equals(this.rows, viewSO.rows) &&
        Objects.equals(this.sortInfo, viewSO.sortInfo) &&
        Objects.equals(this.style, viewSO.style) &&
        Objects.equals(this.type, viewSO.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoHeadHeight, autoSave, columns, description, displayHiddenColumnWithinMirror, filterInfo, frozenColumnCount, groupInfo, hidden, id, lockInfo, name, rowHeightLevel, rows, sortInfo, style, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ViewSO {\n");
    sb.append("    autoHeadHeight: ").append(toIndentedString(autoHeadHeight)).append("\n");
    sb.append("    autoSave: ").append(toIndentedString(autoSave)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayHiddenColumnWithinMirror: ").append(toIndentedString(displayHiddenColumnWithinMirror)).append("\n");
    sb.append("    filterInfo: ").append(toIndentedString(filterInfo)).append("\n");
    sb.append("    frozenColumnCount: ").append(toIndentedString(frozenColumnCount)).append("\n");
    sb.append("    groupInfo: ").append(toIndentedString(groupInfo)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lockInfo: ").append(toIndentedString(lockInfo)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rowHeightLevel: ").append(toIndentedString(rowHeightLevel)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    sortInfo: ").append(toIndentedString(sortInfo)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

