/*
 * APITable <https://github.com/apitable/apitable>
 * Copyright (C) 2022 APITable Ltd. <https://apitable.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.apitable.space.controller;

import java.util.Collections;

import javax.annotation.Resource;
import javax.validation.Valid;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiImplicitParam;
import io.swagger.annotations.ApiOperation;

import com.apitable.interfaces.social.facade.SocialServiceFacade;
import com.apitable.shared.component.scanner.annotation.ApiResource;
import com.apitable.shared.component.scanner.annotation.GetResource;
import com.apitable.shared.component.notification.annotation.Notification;
import com.apitable.shared.component.scanner.annotation.PostResource;
import com.apitable.shared.cache.service.UserSpaceCacheService;
import com.apitable.shared.component.notification.NotificationTemplateId;
import com.apitable.shared.constants.ParamsConstants;
import com.apitable.shared.context.LoginContext;
import com.apitable.shared.context.SessionContext;
import com.apitable.space.ro.SpaceMainAdminChangeOpRo;
import com.apitable.space.vo.MainAdminInfoVo;
import com.apitable.organization.mapper.MemberMapper;
import com.apitable.space.enums.SpaceUpdateOperate;
import com.apitable.space.service.ISpaceInviteLinkService;
import com.apitable.space.service.ISpaceService;
import com.apitable.core.support.ResponseData;

import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Api(tags = "Space - Main Admin Api")
@ApiResource(path = "/space")
public class SpaceMainAdminController {

    @Resource
    private ISpaceService iSpaceService;

    @Resource
    private MemberMapper memberMapper;

    @Resource
    private UserSpaceCacheService userSpaceCacheService;

    @Resource
    private ISpaceInviteLinkService iSpaceInviteLinkService;

    @Resource
    private SocialServiceFacade socialServiceFacade;

    @GetResource(path = "/manager")
    @ApiOperation(value = "Get main admin info")
    @ApiImplicitParam(name = ParamsConstants.SPACE_ID, value = "space id", required = true, dataTypeClass = String.class, paramType = "header", example = "spcyQkKp9XJEl")
    public ResponseData<MainAdminInfoVo> getMainAdminInfo() {
        String spaceId = LoginContext.me().getSpaceId();
        MainAdminInfoVo vo = memberMapper.selectAdminInfoBySpaceId(spaceId);
        return ResponseData.success(vo);
    }

    @Notification(templateId = NotificationTemplateId.SPACE_ADD_PRIMARY_ADMIN)
    @PostResource(path = "/changeManager", tags = "UPDATE_MAIN_ADMIN")
    @ApiOperation(value = "Change main admin")
    @ApiImplicitParam(name = ParamsConstants.SPACE_ID, value = "space id", required = true, dataTypeClass = String.class, paramType = "header", example = "spcyQkKp9XJEl")
    public ResponseData<Void> replace(@RequestBody @Valid SpaceMainAdminChangeOpRo opRo) {
        Long userId = SessionContext.getUserId();
        Long memberId = LoginContext.me().getMemberId();
        String spaceId = LoginContext.me().getSpaceId();
        socialServiceFacade.checkWhetherSpaceCanChangeMainAdmin(spaceId, memberId, opRo.getMemberId(), Collections.singletonList(SpaceUpdateOperate.UPDATE_MAIN_ADMIN));
        Long id = iSpaceService.changeMainAdmin(spaceId, opRo.getMemberId());
        // When the function of inviting all members of the space is turned off,
        // all public invitation links generated by the original main administrator become invalid.
        iSpaceInviteLinkService.delByMemberIdIfNotInvite(spaceId, memberId);
        // delete the relevant cache
        userSpaceCacheService.delete(userId, spaceId);
        userSpaceCacheService.delete(id, spaceId);
        return ResponseData.success();
    }
}
