/* eslint-disable */
// 维格表部分的id（不包含工作目录）

const PREFIX = 'DATASHEET_';

export const VIEW_EXPORT = PREFIX + 'VIEW_EXPORT'; // 视图导出

export const ADD_VIEW_BTN = PREFIX + 'ADD_VIEW_BTN';// 新建视图icon按钮
export const FIELD_CONTEXT = PREFIX + 'FIELD_CONTEXT'; // 维格表表头右击菜单

export const VIEW_TOOL_BAR = PREFIX + 'TOOL_BAR'; // 视图工具栏

export const SWITCH_VIEW_TYPE_CONTAINER = PREFIX + 'SWITCH_VIEW_TYPE_CONTAINER'; // 创建新视图卡片
export const GRID_CUR_COLUMN_TYPE = PREFIX + 'GRID_CUR_COLUMN_TYPE';
export const FILL_HANDLE_AREA = PREFIX + 'FILL_HANDLE_AREA';
export const VIKABY = PREFIX + 'VIKABY';  // vikaby
// 视图标签栏
export const VIEW_TAB_BAR = PREFIX + 'VIEW_TAB_BAR'; // 视图标签栏
export const API_BTN = PREFIX + 'API_BTN'; // 视图标签栏 - api 面板
export const FORM_BTN = PREFIX + 'FORM_BTN';  // 视图标签栏 - 神奇表单
export const WIDGET_BTN = PREFIX + 'WIDGET_BTN';  // 视图标签栏 - 小组件
export const ROBOT_BTN = PREFIX + 'ROBOT_BTN';  // 视图标签栏 - 机器人
export const FORM_LIST_PANEL = PREFIX + 'FORM_LIST_PANEL';  // 视图标签栏 - 神奇表单list
export const TIME_MACHINE_BTN = PREFIX + 'TIME_MACHINE_BTN';  // 视图标签栏 - 时光机


// 维格表内容(维格视图)
export const DOM_CONTAINER = PREFIX + 'DOM_CONTAINER'; // 维格表内容(维格视图)
export const ADD_COLUMN_BTN = PREFIX + 'ADD_COLUMN_BTN'; // 新增列按钮

// 新建视图context
export const VIEW_CREATOR_KANBAN = PREFIX + 'CREATE_KANBAN_VIEW';
export const VIEW_CREATOR_GALLERY = PREFIX + 'CREATE_GALLERY_VIEW';
export const VIEW_CREATOR_GRID = PREFIX + 'CREATE_GRID_VIEW';
export const VIEW_CREATOR_FORM = PREFIX + 'CREATE_FORM_VIEW';
export const VIEW_CREATOR_CALENDAR = PREFIX + 'CREATE_CALENDAR_VIEW';
export const VIEW_CREATOR_ORG_CHART = PREFIX + 'CREATOR_ORG_CHART';
export const VIEW_CREATOR_GANTT = PREFIX + 'CREATE_GANTT_VIEW';
export const VIEW_CREATOR_TABLE = PREFIX + 'CREATE_TABLE';

// 视图操作context
export const VIEW_OPERATION_ITEM_RENAME = PREFIX + 'RENAME_VIEW';
export const VIEW_OPERATION_ITEM_COPY = PREFIX + 'COPY_VIEW';
export const VIEW_OPERATION_ITEM_COPY_FORM = PREFIX + 'COPY_VIEW_FORM';
export const VIEW_OPERATION_ITEM_COPY_MIRROR = PREFIX + 'COPY_VIEW_MIRROR';
export const VIEW_OPERATION_ITEM_EXPORT_VIEW_TO_CSV = PREFIX + 'EXPORT_VIEW_CSV';
export const VIEW_OPERATION_ITEM_EXPORT_VIEW_TO_EXCEL = PREFIX + 'EXPORT_VIEW_EXCEL';
export const VIEW_OPERATION_ITEM_EXPORT_VIEW_TO_IMAGE = PREFIX + 'EXPORT_VIEW_IMAGE';
export const VIEW_OPERATION_ITEM_DELETE = PREFIX + 'DELETE_VIEW';
export const VIEW_OPERATION_ITEM_LOCK = PREFIX + 'LOCK_VIEW';
export const VIEW_OPERATION_ITEM_LOCK_CHECK = PREFIX + 'LOCK_VIEW_CHECK';
export const VIEW_OPERATION_ITEM_CHANGE_AUTO_SAVE = PREFIX + 'CHANGE_AUTO_SAVE';
export const VIEW_OPERATION_ITEM_CHANGE_AUTO_SAVE_CHECK = PREFIX + 'CHANGE_AUTO_SAVE_CHECK';

// 视图列表查看button
export const VIEW_LIST_SHOW_BTN = PREFIX + 'SHOW_VIEW_LIST_BTN';
// 视图列表context
export const VIEW_LIST_CREATE_GRID_VIEW = PREFIX + 'CREATE_GRID_IN_VIEW_LIST';
export const VIEW_LIST_CREATE_KANBAN_VIEW = PREFIX + 'CREATE_KANBAN_IN_VIEW_LIST';
export const VIEW_LIST_CREATE_GALLERY_VIEW = PREFIX + 'CREATE_GALLERY_IN_VIEW_LIST';
export const VIEW_LIST_CREATE_GANTT_VIEW = PREFIX + 'CREATE_GANTT_IN_VIEW_LIST';
export const CREATE_CALENDAR_IN_VIEW_LIST = PREFIX + 'CREATE_CALENDAR_IN_VIEW_LIST';
export const CREATE_ORG_IN_VIEW_LIST = PREFIX + 'CREATE_ORG_IN_VIEW_LIST';

// 悬浮框
export const APPLICATION_JOIN_SPACE_BTN = PREFIX + 'APPLICATION_JOIN_SPACE_BTN';
export const ADD_RECORD_BTN = PREFIX + 'ADD_RECORD_BTN';



// 神奇表单
export const FORM_CONTAINER_SETTING = PREFIX + 'FORM_CONTAINER_SETTING'; // 神奇表单内容页-设置按钮

// 甘特图
export const GANTT_CONFIG_COLOR_HELP = PREFIX + 'GANTT_CONFIG_COLOR_HELP';

// 组织架构图
export const ORG_CHART_RECORD_LIST = PREFIX + 'ORG_CHART_RECORD_LIST'; // 组织架构图-记录列表

// 工具栏
export const TOOL_BAR_VIEW_SETTING = PREFIX + 'TOOL_BAR_VIEW_SETTING'; // 工具栏-新增记录

// 侧边记录卡片
export const SIDE_RECORD_PANEL = PREFIX + 'SIDE_RECORD_PANEL'
