/* eslint-disable */

// 文件夹预览页
const FOLDER_SHOWCASE_PREFIX = 'FOLDER_SHOWCASE_';

export const TITLE = FOLDER_SHOWCASE_PREFIX + 'TITLE' // 标题
export const TITLE_INPUT = FOLDER_SHOWCASE_PREFIX + 'TITLE_INPUT' // 输入框形式的标题
export const DESCRIPTION = FOLDER_SHOWCASE_PREFIX + 'DESCRIPTION' // 描述
export const BTN_MORE = FOLDER_SHOWCASE_PREFIX + 'BTN_MORE' // 更多按钮
export const BTN_SET_PERMISSION = FOLDER_SHOWCASE_PREFIX + 'BTN_SET_PERMISSION' // 更多按钮下的 设置权限 按钮
export const FIRST_NODE = FOLDER_SHOWCASE_PREFIX + 'FIRST_NODE'; // 文件夹预览页面的第一个node
export const NODES_CONTAINER = FOLDER_SHOWCASE_PREFIX + 'NODES_CONTAINER'; // 子节点的父容器