const PREFIX = 'HOME__';
// 登录方式
export const LOGIN_TYPE_QQ = PREFIX + 'LOGIN_TYPE_QQ';
export const LOGIN_TYPE_WECHAT = PREFIX + 'LOGIN_TYPE_WECHAT';
export const LOGIN_TYPE_DINGDING= PREFIX + 'LOGIN_TYPE_DINGDING';
export const LOGIN_TYPE_LARK = PREFIX + 'LOGIN_TYPE_LARK';
