/* eslint_disable */
// 工作台——工作目录ID

const PREFIX = 'WORKBENCH_SIDE_';
// 星标以及工作目录的container
export const NODE_WRAPPER = PREFIX + 'NODE_WRAPPER';
export const ADD_NODE_BTN = PREFIX + 'ADD_NODE_BTN';

// 回收站
export const RECYCLE_BIN = PREFIX + 'RECYCLE_BIN';
// 使用模版
export const TO_SPACE_TEMPLATE = PREFIX + 'TO_SPACE_TEMPLATE';

// 工作目录节点的操作菜单context
export const OPERATE_ITEM_RENAME_NODE = PREFIX + 'RENAME_NODE';
export const OPERATE_ITEM_STAR_NODE = PREFIX + 'STAR_NODE';
export const OPERATE_ITEM_COPY_NODE = PREFIX + 'COPY_NODE';
export const OPERATE_ITEM_COPY_NODE_URL = PREFIX + 'COPY_NODE_URL';
export const OPERATE_ITEM_EXPORT_NODE_CSV = PREFIX + 'EXPORT_NODE_CSV';
export const OPERATE_ITEM_EXPORT_NODE_EXCEL = PREFIX + 'EXPORT_NODE_EXCEL';
export const OPERATE_ITEM_SET_PERMISSIONS = PREFIX + 'SET_PERMISSIONS';
export const OPERATE_ITEM_SHARE_NODE = PREFIX + 'SHARE_NODE';
export const OPERATE_ITEM_SAVE_AS_TEMPLATE = PREFIX + 'SAVE_AS_TEMPLATE';
export const OPERATE_ITEM_DELETE_NODE = PREFIX + 'DELETE_NODE';
export const OPERATE_ITEM_ADD_DATASHEET = PREFIX + 'ADD_DATASHEET';

// 收集表
export const FORM_USE_GUIDE_BTN = PREFIX + 'FORM_USE_GUIDE_BTN';

export const NODE_EXPORT = PREFIX + 'NODE_EXPORT';
export const NODE_IMPORT = PREFIX + 'NODE_IMPORT';
export const NEW_DATASHEET = PREFIX + 'NEW_DATASHEET';
export const NEW_FORM = PREFIX + 'NEW_FORM';
export const NEW_FOLDER = PREFIX + 'NEW_FOLDER';
export const NEW_FORM_TEMPLATE = PREFIX + 'NEW_FORM_TEMPLATE';
export const NEW_DASHBOARD = PREFIX + 'NEW_DASHBOARD';
export const NODE_INFO = PREFIX + 'NODE_INFO';
