name: build-apitable

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  buildpush:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    env:
      APITABLE_DOCKER_HUB_TOKEN: ${{ secrets.APITABLE_DOCKER_HUB_TOKEN }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Build APITable and Push
        run: |
          make buildpush-docker
